# Package information
LIBRARY = SelectionTools
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

INCLUDES += -I../
INCLUDES += -I./
#INCLUDES += -I../RootCore/DGTriggerReweight/
#INCLUDES += -I../RootCore/JetResolution/
#INCLUDES += -I../RootCore/ReweightUtils/
#INCLUDES += -I../RootCore/SUSYTools/
#INCLUDES += -I../RootCore/TriggerMatch/
INCLUDES += -I../RootCore/ApplyJetCalibration/
INCLUDES += -I../RootCore/GoodRunsLists/
INCLUDES += -I../RootCore/MissingETUtility/
INCLUDES += -I../RootCore/MuonMomentumCorrections/
INCLUDES += -I../RootCore/egammaAnalysisUtils/
INCLUDES += -I../RootCore/egammaEvent/

# Include the generic compilation rules
include $(SFRAME_DIR)/Makefile.common
