
Type:             mc
OutputLevel:      INFO
OutputDirectory:  /tmp/${USER}/
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       176802.Herwigpp_UEEE3_CTEQ6L1_sM_wA_stau_C1N2_250_0_N1_100_0

input_tree_name:  susy
output_tree_name: output
is_egamma_stream: True

# UserConfigFile: /exports/project/data_d07_3/ehines/SusyFrame/Susy_p1328/SFrame/../run/pcpenn_configs/user_config.cut_flow.mc.yml
UserConfigFile: ${SFRAME_DIR}/../run/local_configs/user_config.cut_flow.mc.yml

InputFiles:
  - /afs/cern.ch/user/b/bjackson/work/public/mc12_8TeV.176802.Herwigpp_UEEE3_CTEQ6L1_sM_wA_stau_C1N2_250_0_N1_100_0.merge.NTUP_SUSY.e1721_s1581_s1586_r3658_r3549_p1512/NTUP_SUSY.01268024._000001.root
  - /afs/cern.ch/user/b/bjackson/work/public/mc12_8TeV.176802.Herwigpp_UEEE3_CTEQ6L1_sM_wA_stau_C1N2_250_0_N1_100_0.merge.NTUP_SUSY.e1721_s1581_s1586_r3658_r3549_p1512/NTUP_SUSY.01268024._000002.root


