
Type:             mc
OutputLevel:      INFO
OutputDirectory:  /tmp/${USER}/
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       126892.Sherpa_CT10_lllnu_WW

input_tree_name:  susy
output_tree_name: output
is_egamma_stream: True


# UserConfigFile: /exports/project/data_d07_3/ehines/SusyFrame/Susy_p1328/SFrame/../run/pcpenn_configs/user_config.cut_flow.mc.yml
UserConfigFile: ${SFRAME_DIR}/../run/local_configs/user_config.cut_flow.mc.yml

InputFiles:
  - root://eosatlas//eos/atlas/user/b/bjackson/mc12/mc12_8TeV.126892.Sherpa_CT10_llnunu_WW.merge.NTUP_SUSY.e1434_s1499_s1504_r3658_r3549_p1328_tid01116020_00/NTUP_SUSY.01116020._000001.root.1   
