
Type:             mc
OutputLevel:      INFO
OutputDirectory:  /tmp/${USER}/
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       174839.Herwigpp_UEEE3_CTEQ6L1_simplifiedModel_wA_noslep_lepW_71

input_tree_name:  susy
output_tree_name: output
is_egamma_stream: True

# UserConfigFile: /exports/project/data_d07_3/ehines/SusyFrame/Susy_p1328/SFrame/../run/pcpenn_configs/user_config.cut_flow.mc.yml
UserConfigFile: ${SFRAME_DIR}/../run/local_configs/user_config.cut_flow.mc.yml

InputFiles:
  - /afs/cern.ch/user/b/bjackson/work/private/mc12/mc12_8TeV.174839.Herwigpp_UEEE3_CTEQ6L1_simplifiedModel_wA_noslep_lepW_71.merge.NTUP_SUSY.e1615_s1499_s1504_r3658_r3549_p1512_tid01272932_00/NTUP_SUSY.01272932._000001.root.1
  - /afs/cern.ch/user/b/bjackson/work/private/mc12/mc12_8TeV.174839.Herwigpp_UEEE3_CTEQ6L1_simplifiedModel_wA_noslep_lepW_71.merge.NTUP_SUSY.e1615_s1499_s1504_r3658_r3549_p1512_tid01272932_00/NTUP_SUSY.01272932._000002.root.1

