// Dear emacs, this is -*- c++ -*-
// -------------------------------------------------------------
//             Code produced by D3PDMakerReader
//
//  author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
// -------------------------------------------------------------
#ifndef D3PDREADER_ElectronD3PDObject_H
#define D3PDREADER_ElectronD3PDObject_H

#include <map>
#include <vector>
using std::vector;

#include <TObject.h>
#include <TString.h>

#include "VarHandle.h"
#include "VarProxy.h"

class TTree;

namespace D3PDReader {

   // Forward declaration(s):
   class ElectronD3PDObject;

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-07
    *  OS   = Linux / 2.6.18-274.18.1.el5
    *  user = bjackson
    */
   class ElectronD3PDObjectElement : public TObject {

      friend class ElectronD3PDObject;

   protected:
      /// Constructor only visible to ElectronD3PDObject
      ElectronD3PDObjectElement( size_t index, const ElectronD3PDObject& parent, bool is_data = true );

   public:
      /// Copy constructor
      ElectronD3PDObjectElement( const ElectronD3PDObjectElement& parent, bool is_data = true );

      VarProxy< float > E;
      VarProxy< float > Et;
      VarProxy< float > pt;
      VarProxy< float > m;
      VarProxy< float > eta;
      VarProxy< float > phi;
      VarProxy< float > px;
      VarProxy< float > py;
      VarProxy< float > pz;
      VarProxy< float > charge;
      VarProxy< int > author;
      VarProxy< unsigned int > OQ;
      /// Number of tracks for the first conversion candidate; 0 if no conversion or if there are more than two tracks.
      VarProxy< int > convFlag;
      /// Number of conversion vertices.
      VarProxy< int > nConv;
// MC only
      /// MC particle type, from classifier tool.
      VarProxy< int > type;
      /// MC particle origin, from classifier tool.
      VarProxy< int > origin;
      VarProxy< float > truth_E;
      VarProxy< float > truth_pt;
      VarProxy< float > truth_eta;
      VarProxy< float > truth_phi;
      VarProxy< int > truth_type;
      VarProxy< int > truth_status;
      VarProxy< int > truth_barcode;
      VarProxy< int > truth_mothertype;
      VarProxy< int > truth_motherbarcode;
      VarProxy< int > truth_hasHardBrem;
      /// Index in mc_
      VarProxy< int > truth_index;
      VarProxy< int > truth_matched;
// end MC only
      VarProxy< int > loosePP;
      VarProxy< int > loosePPIso;
      VarProxy< int > mediumPP;
      VarProxy< int > mediumPPIso;
      VarProxy< int > tightPP;
      VarProxy< int > tightPPIso;
      /// [detail 9]
      VarProxy< float > Ethad;
      /// [detail 8]
      VarProxy< float > Ethad1;
      /// [detail 11]
      VarProxy< float > f1;
      /// [detail 28]
      VarProxy< float > fside;
      /// [detail 37]
      VarProxy< float > wstot;
      /// [detail 39]
      VarProxy< float > emaxs1;
      /// [detail 25]
      VarProxy< float > weta2;
      /// [detail 12]
      VarProxy< float > f3;
      /// [detail 0]
      VarProxy< float > Etcone45;
      /// [detail 285]
      VarProxy< float > Etcone15;
      /// [detail 1]
      VarProxy< float > Etcone20;
      /// [detail 286]
      VarProxy< float > Etcone25;
      /// [detail 2]
      VarProxy< float > Etcone30;
      /// [detail 287]
      VarProxy< float > Etcone35;
      /// [detail 3]
      VarProxy< float > Etcone40;
      /// [detail 293]
      VarProxy< float > ptcone20;
      /// [detail 241]
      VarProxy< float > ptcone30;
      /// [detail 294]
      VarProxy< float > ptcone40;
      /// [detail 295]
      VarProxy< float > nucone20;
      /// [detail 296]
      VarProxy< float > nucone30;
      /// [detail 297]
      VarProxy< float > nucone40;
      /// [detail 45]
      VarProxy< float > deltaeta1;
      /// [detail 46]
      VarProxy< float > deltaeta2;
      /// [detail 50]
      VarProxy< float > deltaphi2;
      /// [detail 288]Do we expect to see a hit from this track in the B pixel layer?
      VarProxy< float > expectHitInBLayer;
      /// [detail 274]Transverse impact parameter with respect to the beam spot.
      VarProxy< float > trackd0_physics;
      /// [detail 248]Eta position at sampling 1 for track extrapolated from the last hit.
      VarProxy< float > etaSampling1;
      VarProxy< float > reta;
      /// [detail 306]
      VarProxy< float > topoEtcone20;
      /// [detail 307]
      VarProxy< float > topoEtcone30;
      /// [detail 308]
      VarProxy< float > topoEtcone40;
      /// [detail 331]
      VarProxy< float > nucone20_zpv05;
      /// [detail 332]
      VarProxy< float > nucone30_zpv05;
      /// [detail 333]
      VarProxy< float > nucone40_zpv05;
      VarProxy< float > etas0;
      VarProxy< float > etas1;
      VarProxy< float > etas2;
      VarProxy< float > etas3;
      VarProxy< float > cl_E;
      VarProxy< float > cl_pt;
      VarProxy< float > cl_eta;
      VarProxy< float > cl_phi;
      VarProxy< float > trackd0;
      VarProxy< float > trackz0;
      VarProxy< float > trackphi;
      VarProxy< float > tracktheta;
      VarProxy< float > trackqoverp;
      VarProxy< float > trackpt;
      VarProxy< float > tracketa;
      VarProxy< int > nBLHits;
      VarProxy< int > nPixHits;
      VarProxy< int > nSCTHits;
      VarProxy< int > nTRTHits;
      VarProxy< int > nTRTHighTHits;
      VarProxy< int > nTRTXenonHits;
      VarProxy< int > nPixHoles;
      VarProxy< int > nSCTHoles;
      VarProxy< int > nTRTHoles;
      VarProxy< int > nBLayerOutliers;
      VarProxy< int > nPixelOutliers;
      VarProxy< int > nSCTOutliers;
      VarProxy< int > nTRTOutliers;
      VarProxy< int > nTRTHighTOutliers;
      VarProxy< int > nContribPixelLayers;
      VarProxy< int > expectBLayerHit;
      VarProxy< int > nSiHits;
      VarProxy< float > TRTHighTHitsRatio;
      VarProxy< float > TRTHighTOutliersRatio;
      VarProxy< float > trackd0pv;
      VarProxy< float > trackz0pv;
      /// Uncertainty on transverse impact parameter.
      VarProxy< float > tracksigd0pv;
      /// Uncertainty on longitudinal impact parameter.
      VarProxy< float > tracksigz0pv;
      VarProxy< float > trackIPEstimate_d0_unbiasedpvunbiased;
      VarProxy< float > trackIPEstimate_z0_unbiasedpvunbiased;
      VarProxy< float > trackIPEstimate_sigd0_unbiasedpvunbiased;
      VarProxy< float > trackIPEstimate_sigz0_unbiasedpvunbiased;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_Etcone40_ED_corrected] 
      VarProxy< float > Etcone40_ED_corrected;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_Etcone40_corrected] 
      VarProxy< float > Etcone40_corrected;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_topoEtcone20_corrected] 
      VarProxy< float > topoEtcone20_corrected;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_topoEtcone30_corrected] 
      VarProxy< float > topoEtcone30_corrected;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_topoEtcone40_corrected] 
      VarProxy< float > topoEtcone40_corrected;
      VarProxy< int > nucone20_trk500MeV;
      VarProxy< int > nucone30_trk500MeV;
      VarProxy< int > nucone40_trk500MeV;
      VarProxy< vector<float> > MET_Egamma10NoTau_wpx;
      VarProxy< vector<float> > MET_Egamma10NoTau_wpy;
      VarProxy< vector<float> > MET_Egamma10NoTau_wet;
      VarProxy< vector<unsigned int> > MET_Egamma10NoTau_statusWord;


bool is_data; // ~bj 

      ClassDef( ElectronD3PDObjectElement, 0 )

   }; // class ElectronD3PDObjectElement

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-07
    *  OS   = Linux / 2.6.18-274.18.1.el5
    *  user = bjackson
    */
   class ElectronD3PDObject : public TObject {

   public:
      /// Constructor used when reading from a TTree
      ElectronD3PDObject( const ::Long64_t& master, const char* prefix = "el_", bool is_data = true );
      /// Constructor when the object is only used for writing data out
      ElectronD3PDObject( const char* prefix = "el_", bool is_data = true );

      /// Get the currently configured prefix value
      const char* GetPrefix() const;
      /// Set the prefix for the variables
      void SetPrefix( const char* prefix );

      /// Connect the object to an input TTree
      void ReadFrom( ::TTree* tree );
      /// Connect the object to an output TTree
      void WriteTo( ::TTree* tree );

      /// Turn (selected) branches either on or off
      void SetActive( ::Bool_t active = kTRUE,
                      const ::TString& pattern = ".*" );
      /// Read in all the variables that we need to write out as well
      void ReadAllActive();

      /// Clear the container. Useful when writing new branches.
      void Clear( Option_t* option = "" );
      /// Add one element to an output collection
      ElectronD3PDObject& Add( const ElectronD3PDObjectElement& el );

      /// Access a proxy class describing one element of the container
      ElectronD3PDObjectElement& operator[]( size_t index );
      /// Access a proxy class describing one element of the container (constant version)
      const ElectronD3PDObjectElement& operator[]( size_t index ) const;
      /// Add one element to an output collection
      ElectronD3PDObject& operator+=( const ElectronD3PDObjectElement& el );

      /// Number of ntuple rows.
      VarHandle< Int_t > n;
      VarHandle< vector<float>* > E;
      VarHandle< vector<float>* > Et;
      VarHandle< vector<float>* > pt;
      VarHandle< vector<float>* > m;
      VarHandle< vector<float>* > eta;
      VarHandle< vector<float>* > phi;
      VarHandle< vector<float>* > px;
      VarHandle< vector<float>* > py;
      VarHandle< vector<float>* > pz;
      VarHandle< vector<float>* > charge;
      VarHandle< vector<int>* > author;
      VarHandle< vector<unsigned int>* > OQ;
      /// Number of tracks for the first conversion candidate; 0 if no conversion or if there are more than two tracks.
      VarHandle< vector<int>* > convFlag;
      /// Number of conversion vertices.
      VarHandle< vector<int>* > nConv;
// MC only
      /// MC particle type, from classifier tool.
      VarHandle< vector<int>* > type;
      /// MC particle origin, from classifier tool.
      VarHandle< vector<int>* > origin;
      VarHandle< vector<float>* > truth_E;
      VarHandle< vector<float>* > truth_pt;
      VarHandle< vector<float>* > truth_eta;
      VarHandle< vector<float>* > truth_phi;
      VarHandle< vector<int>* > truth_type;
      VarHandle< vector<int>* > truth_status;
      VarHandle< vector<int>* > truth_barcode;
      VarHandle< vector<int>* > truth_mothertype;
      VarHandle< vector<int>* > truth_motherbarcode;
      VarHandle< vector<int>* > truth_hasHardBrem;
      /// Index in mc_
      VarHandle< vector<int>* > truth_index;
      VarHandle< vector<int>* > truth_matched;
// end MC only
      VarHandle< vector<int>* > loosePP;
      VarHandle< vector<int>* > loosePPIso;
      VarHandle< vector<int>* > mediumPP;
      VarHandle< vector<int>* > mediumPPIso;
      VarHandle< vector<int>* > tightPP;
      VarHandle< vector<int>* > tightPPIso;
      /// [detail 9]
      VarHandle< vector<float>* > Ethad;
      /// [detail 8]
      VarHandle< vector<float>* > Ethad1;
      /// [detail 11]
      VarHandle< vector<float>* > f1;
      /// [detail 28]
      VarHandle< vector<float>* > fside;
      /// [detail 37]
      VarHandle< vector<float>* > wstot;
      /// [detail 39]
      VarHandle< vector<float>* > emaxs1;
      /// [detail 25]
      VarHandle< vector<float>* > weta2;
      /// [detail 12]
      VarHandle< vector<float>* > f3;
      /// [detail 0]
      VarHandle< vector<float>* > Etcone45;
      /// [detail 285]
      VarHandle< vector<float>* > Etcone15;
      /// [detail 1]
      VarHandle< vector<float>* > Etcone20;
      /// [detail 286]
      VarHandle< vector<float>* > Etcone25;
      /// [detail 2]
      VarHandle< vector<float>* > Etcone30;
      /// [detail 287]
      VarHandle< vector<float>* > Etcone35;
      /// [detail 3]
      VarHandle< vector<float>* > Etcone40;
      /// [detail 293]
      VarHandle< vector<float>* > ptcone20;
      /// [detail 241]
      VarHandle< vector<float>* > ptcone30;
      /// [detail 294]
      VarHandle< vector<float>* > ptcone40;
      /// [detail 295]
      VarHandle< vector<float>* > nucone20;
      /// [detail 296]
      VarHandle< vector<float>* > nucone30;
      /// [detail 297]
      VarHandle< vector<float>* > nucone40;
      /// [detail 45]
      VarHandle< vector<float>* > deltaeta1;
      /// [detail 46]
      VarHandle< vector<float>* > deltaeta2;
      /// [detail 50]
      VarHandle< vector<float>* > deltaphi2;
      /// [detail 288]Do we expect to see a hit from this track in the B pixel layer?
      VarHandle< vector<float>* > expectHitInBLayer;
      /// [detail 274]Transverse impact parameter with respect to the beam spot.
      VarHandle< vector<float>* > trackd0_physics;
      /// [detail 248]Eta position at sampling 1 for track extrapolated from the last hit.
      VarHandle< vector<float>* > etaSampling1;
      VarHandle< vector<float>* > reta;
      /// [detail 306]
      VarHandle< vector<float>* > topoEtcone20;
      /// [detail 307]
      VarHandle< vector<float>* > topoEtcone30;
      /// [detail 308]
      VarHandle< vector<float>* > topoEtcone40;
      /// [detail 331]
      VarHandle< vector<float>* > nucone20_zpv05;
      /// [detail 332]
      VarHandle< vector<float>* > nucone30_zpv05;
      /// [detail 333]
      VarHandle< vector<float>* > nucone40_zpv05;
      VarHandle< vector<float>* > etas0;
      VarHandle< vector<float>* > etas1;
      VarHandle< vector<float>* > etas2;
      VarHandle< vector<float>* > etas3;
      VarHandle< vector<float>* > cl_E;
      VarHandle< vector<float>* > cl_pt;
      VarHandle< vector<float>* > cl_eta;
      VarHandle< vector<float>* > cl_phi;
      VarHandle< vector<float>* > trackd0;
      VarHandle< vector<float>* > trackz0;
      VarHandle< vector<float>* > trackphi;
      VarHandle< vector<float>* > tracktheta;
      VarHandle< vector<float>* > trackqoverp;
      VarHandle< vector<float>* > trackpt;
      VarHandle< vector<float>* > tracketa;
      VarHandle< vector<int>* > nBLHits;
      VarHandle< vector<int>* > nPixHits;
      VarHandle< vector<int>* > nSCTHits;
      VarHandle< vector<int>* > nTRTHits;
      VarHandle< vector<int>* > nTRTHighTHits;
      VarHandle< vector<int>* > nTRTXenonHits;
      VarHandle< vector<int>* > nPixHoles;
      VarHandle< vector<int>* > nSCTHoles;
      VarHandle< vector<int>* > nTRTHoles;
      VarHandle< vector<int>* > nBLayerOutliers;
      VarHandle< vector<int>* > nPixelOutliers;
      VarHandle< vector<int>* > nSCTOutliers;
      VarHandle< vector<int>* > nTRTOutliers;
      VarHandle< vector<int>* > nTRTHighTOutliers;
      VarHandle< vector<int>* > nContribPixelLayers;
      VarHandle< vector<int>* > expectBLayerHit;
      VarHandle< vector<int>* > nSiHits;
      VarHandle< vector<float>* > TRTHighTHitsRatio;
      VarHandle< vector<float>* > TRTHighTOutliersRatio;
      VarHandle< vector<float>* > trackd0pv;
      VarHandle< vector<float>* > trackz0pv;
      /// Uncertainty on transverse impact parameter.
      VarHandle< vector<float>* > tracksigd0pv;
      /// Uncertainty on longitudinal impact parameter.
      VarHandle< vector<float>* > tracksigz0pv;
      VarHandle< vector<float>* > trackIPEstimate_d0_unbiasedpvunbiased;
      VarHandle< vector<float>* > trackIPEstimate_z0_unbiasedpvunbiased;
      VarHandle< vector<float>* > trackIPEstimate_sigd0_unbiasedpvunbiased;
      VarHandle< vector<float>* > trackIPEstimate_sigz0_unbiasedpvunbiased;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_Etcone40_ED_corrected] 
      VarHandle< vector<float>* > Etcone40_ED_corrected;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_Etcone40_corrected] 
      VarHandle< vector<float>* > Etcone40_corrected;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_topoEtcone20_corrected] 
      VarHandle< vector<float>* > topoEtcone20_corrected;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_topoEtcone30_corrected] 
      VarHandle< vector<float>* > topoEtcone30_corrected;
      /// [UserData: egammaD3PDAnalysis::_ElectronAODCollection_topoEtcone40_corrected] 
      VarHandle< vector<float>* > topoEtcone40_corrected;
      VarHandle< vector<int>* > nucone20_trk500MeV;
      VarHandle< vector<int>* > nucone30_trk500MeV;
      VarHandle< vector<int>* > nucone40_trk500MeV;
      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_wpx;
      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_wpy;
      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_wet;
      VarHandle< vector<vector<unsigned int> >* > MET_Egamma10NoTau_statusWord;

   private:
      mutable std::vector< ElectronD3PDObjectElement > fProxies; ///< Internal list of proxy objects
      std::map< ::TString, VarHandleBase* > fHandles; ///< Book-keeper of the VarHandle members
      const ::Bool_t fFromInput; ///< Flag specifying if object is used for D3PD reading
      const ::TString fPrefix; ///< Prefix to the branch names


bool is_data; // ~bj 

      ClassDef( ElectronD3PDObject, 0 )

   }; // class ElectronD3PDObject

} // namespace D3PDReader

#endif // D3PDREADER_ElectronD3PDObject_H
