// Dear emacs, this is -*- c++ -*-
// -------------------------------------------------------------
//             Code produced by D3PDMakerReader
//
//  author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
// -------------------------------------------------------------
#ifndef D3PDREADER_JetD3PDObject_H
#define D3PDREADER_JetD3PDObject_H

#include <map>
#include <vector>
using std::vector;

#include <TObject.h>
#include <TString.h>

#include "VarHandle.h"
#include "VarProxy.h"

class TTree;

namespace D3PDReader {

   // Forward declaration(s):
   class JetD3PDObject;

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-07
    *  OS   = Linux / 2.6.18-274.18.1.el5
    *  user = bjackson
    */
   class JetD3PDObjectElement : public TObject {

      friend class JetD3PDObject;

   protected:
      /// Constructor only visible to JetD3PDObject
      JetD3PDObjectElement( size_t index, const JetD3PDObject& parent, bool is_data = true );

   public:
      /// Copy constructor
      JetD3PDObjectElement( const JetD3PDObjectElement& parent, bool is_data = true );

      VarProxy< vector<float> > MET_Egamma10NoTau_wpx;
      VarProxy< vector<float> > MET_Egamma10NoTau_wpy;
      VarProxy< vector<float> > MET_Egamma10NoTau_wet;
      VarProxy< vector<unsigned int> > MET_Egamma10NoTau_statusWord;
      VarProxy< vector<float> > MET_Egamma10NoTau_STVF_wpx;
      VarProxy< vector<float> > MET_Egamma10NoTau_STVF_wpy;
      VarProxy< vector<float> > MET_Egamma10NoTau_STVF_wet;
      VarProxy< vector<unsigned int> > MET_Egamma10NoTau_STVF_statusWord;
// -- slimmed --       VarProxy< vector<float> > MET_LooseEgamma10NoTau_wpx;
// -- slimmed --       VarProxy< vector<float> > MET_LooseEgamma10NoTau_wpy;
// -- slimmed --       VarProxy< vector<float> > MET_LooseEgamma10NoTau_wet;
// -- slimmed --       VarProxy< vector<unsigned int> > MET_LooseEgamma10NoTau_statusWord;
// -- slimmed --       VarProxy< vector<float> > MET_wpx;
// -- slimmed --       VarProxy< vector<float> > MET_wpy;
// -- slimmed --       VarProxy< vector<float> > MET_wet;
// -- slimmed --       VarProxy< vector<unsigned int> > MET_statusWord;
// -- slimmed --       VarProxy< vector<float> > MET_STVF_wpx;
// -- slimmed --       VarProxy< vector<float> > MET_STVF_wpy;
// -- slimmed --       VarProxy< vector<float> > MET_STVF_wet;
// -- slimmed --       VarProxy< vector<unsigned int> > MET_STVF_statusWord;
      VarProxy< float > E;
      VarProxy< float > pt;
      VarProxy< float > m;
      VarProxy< float > eta;
      VarProxy< float > phi;
      VarProxy< float > EtaOrigin;
      VarProxy< float > PhiOrigin;
      VarProxy< float > MOrigin;
      VarProxy< float > EtaOriginEM;
      VarProxy< float > PhiOriginEM;
      VarProxy< float > MOriginEM;
// -- slimmed --       VarProxy< float > WIDTH;
// -- slimmed --       VarProxy< float > n90;
// -- slimmed --       VarProxy< float > Timing;
      VarProxy< float > LArQuality;
      VarProxy< float > nTrk;
      VarProxy< float > sumPtTrk;
      VarProxy< float > OriginIndex;
      VarProxy< float > HECQuality;
      VarProxy< float > NegativeE;
      VarProxy< float > AverageLArQF;
      // ~~~
// -- slimmed --       VarProxy< float > YFlip12;
// -- slimmed --       VarProxy< float > YFlip23;
// -- slimmed --       VarProxy< float > BCH_CORR_CELL;
// -- slimmed --       VarProxy< float > BCH_CORR_DOTX;
// -- slimmed --       VarProxy< float > BCH_CORR_JET;
// -- slimmed --       VarProxy< float > BCH_CORR_JET_FORCELL;
      VarProxy< float > ENG_BAD_CELLS;
      VarProxy< float > N_BAD_CELLS;
      VarProxy< float > N_BAD_CELLS_CORR;
      VarProxy< float > BAD_CELLS_CORR_E;
// -- slimmed --       VarProxy< float > NumTowers;
// -- slimmed --       VarProxy< float > ootFracCells5;
// -- slimmed --       VarProxy< float > ootFracCells10;
// -- slimmed --       VarProxy< float > ootFracClusters5;
// -- slimmed --       VarProxy< float > ootFracClusters10;
      // ~~~
      VarProxy< int > SamplingMax;
      VarProxy< float > fracSamplingMax;
      VarProxy< float > hecf;
// -- slimmed --       VarProxy< float > tgap3f;
// -- slimmed --       VarProxy< int > isUgly;
// -- slimmed --       VarProxy< int > isBadLooseMinus;
// -- slimmed --       VarProxy< int > isBadLoose;
// -- slimmed --       VarProxy< int > isBadMedium;
// -- slimmed --       VarProxy< int > isBadTight;
      VarProxy< float > emfrac;
      VarProxy< float > Offset;
      VarProxy< float > EMJES;
      VarProxy< float > EMJES_EtaCorr;
      VarProxy< float > EMJESnooffset;
      VarProxy< float > GCWJES;
      VarProxy< float > GCWJES_EtaCorr;
      VarProxy< float > CB;
      VarProxy< float > LCJES;
      VarProxy< float > emscale_E;
      VarProxy< float > emscale_pt;
      VarProxy< float > emscale_m;
      VarProxy< float > emscale_eta;
      VarProxy< float > emscale_phi;
      VarProxy< float > jvtx_x;
      VarProxy< float > jvtx_y;
      VarProxy< float > jvtx_z;
      VarProxy< float > jvtxf;
      VarProxy< vector<float> > jvtxfFull;
      VarProxy< float > GSCFactorF;
      VarProxy< float > WidthFraction;
      VarProxy< float > e_PreSamplerB;
// -- slimmed --       VarProxy< float > e_EMB1;
// -- slimmed --       VarProxy< float > e_EMB2;
// -- slimmed --       VarProxy< float > e_EMB3;
// -- slimmed --       VarProxy< float > e_PreSamplerE;
// -- slimmed --       VarProxy< float > e_EME1;
// -- slimmed --       VarProxy< float > e_EME2;
// -- slimmed --       VarProxy< float > e_EME3;
// -- slimmed --       VarProxy< float > e_HEC0;
// -- slimmed --       VarProxy< float > e_HEC1;
// -- slimmed --       VarProxy< float > e_HEC2;
// -- slimmed --       VarProxy< float > e_HEC3;
// -- slimmed --       VarProxy< float > e_TileBar0;
// -- slimmed --       VarProxy< float > e_TileBar1;
// -- slimmed --       VarProxy< float > e_TileBar2;
// -- slimmed --       VarProxy< float > e_TileGap1;
// -- slimmed --       VarProxy< float > e_TileGap2;
// -- slimmed --       VarProxy< float > e_TileGap3;
// -- slimmed --       VarProxy< float > e_TileExt0;
// -- slimmed --       VarProxy< float > e_TileExt1;
// -- slimmed --       VarProxy< float > e_TileExt2;
// -- slimmed --       VarProxy< float > e_FCAL0;
// -- slimmed --       VarProxy< float > e_FCAL1;
// -- slimmed --       VarProxy< float > e_FCAL2;
// -- slimmed --       VarProxy< int > Nconst;
// -- slimmed --       VarProxy< vector<float> > ptconst_default;
// -- slimmed --       VarProxy< vector<float> > econst_default;
// -- slimmed --       VarProxy< vector<float> > etaconst_default;
// -- slimmed --       VarProxy< vector<float> > phiconst_default;
// -- slimmed --       VarProxy< vector<float> > weightconst_default;
      VarProxy< float > constscale_E;
      VarProxy< float > constscale_pt;
      VarProxy< float > constscale_m;
      VarProxy< float > constscale_eta;
      VarProxy< float > constscale_phi;
      VarProxy< float > flavor_weight_Comb;
      VarProxy< float > flavor_weight_IP2D;
      VarProxy< float > flavor_weight_IP3D;
      VarProxy< float > flavor_weight_SV0;
      VarProxy< float > flavor_weight_SV1;
      VarProxy< float > flavor_weight_SV2;
      VarProxy< float > flavor_weight_SoftMuonTagChi2;
      VarProxy< float > flavor_weight_SecondSoftMuonTagChi2;
      VarProxy< float > flavor_weight_JetFitterTagNN;
      VarProxy< float > flavor_weight_JetFitterCOMBNN;
      VarProxy< float > flavor_weight_MV1;
      VarProxy< float > flavor_weight_MV2;
      VarProxy< float > flavor_weight_GbbNN;
// MC only
      VarProxy< int > flavor_truth_label;
      VarProxy< float > flavor_truth_dRminToB;
      VarProxy< float > flavor_truth_dRminToC;
      VarProxy< float > flavor_truth_dRminToT;
      VarProxy< int > flavor_truth_BHadronpdg;
      VarProxy< float > flavor_truth_vx_x;
      VarProxy< float > flavor_truth_vx_y;
      VarProxy< float > flavor_truth_vx_z;
// end MC only
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_ip2d_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_ip2d_pb;
// -- slimmed --       VarProxy< int > flavor_component_ip2d_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_ip2d_ntrk;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_ip3d_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_ip3d_pb;
// -- slimmed --       VarProxy< int > flavor_component_ip3d_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_ip3d_ntrk;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_sv1_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_sv1_pb;
// -- slimmed --       VarProxy< int > flavor_component_sv1_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_sv2_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_sv2_pb;
// -- slimmed --       VarProxy< int > flavor_component_sv2_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfit_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfit_pb;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfit_pc;
// -- slimmed --       VarProxy< int > flavor_component_jfit_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfitcomb_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfitcomb_pb;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfitcomb_pc;
// -- slimmed --       VarProxy< int > flavor_component_jfitcomb_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_jfit_nvtx;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_jfit_nvtx1t;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_jfit_ntrkAtVx;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfit_efrc;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfit_mass;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfit_sig3d;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfit_deltaPhi;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_jfit_deltaEta;
// -- slimmed --       VarProxy< int > flavor_component_svp_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_svp_ntrkv;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_svp_ntrkj;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_svp_n2t;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_svp_mass;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_svp_efrc;
// -- slimmed --       VarProxy< float > flavor_component_svp_x;
// -- slimmed --       VarProxy< float > flavor_component_svp_y;
// -- slimmed --       VarProxy< float > flavor_component_svp_z;
// -- slimmed --       VarProxy< float > flavor_component_svp_err_x;
// -- slimmed --       VarProxy< float > flavor_component_svp_err_y;
// -- slimmed --       VarProxy< float > flavor_component_svp_err_z;
// -- slimmed --       VarProxy< float > flavor_component_svp_cov_xy;
// -- slimmed --       VarProxy< float > flavor_component_svp_cov_xz;
// -- slimmed --       VarProxy< float > flavor_component_svp_cov_yz;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_svp_chi2;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_svp_ndof;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_svp_ntrk;
// -- slimmed --       VarProxy< int > flavor_component_sv0p_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_sv0p_ntrkv;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_sv0p_ntrkj;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_sv0p_n2t;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_sv0p_mass;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_sv0p_efrc;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_x;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_y;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_z;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_err_x;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_err_y;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_err_z;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_cov_xy;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_cov_xz;
// -- slimmed --       VarProxy< float > flavor_component_sv0p_cov_yz;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< float > flavor_component_sv0p_chi2;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_sv0p_ndof;
      /// UNDOCUMENTED
// -- slimmed --       VarProxy< int > flavor_component_sv0p_ntrk;
      /// Number of ntuple rows.
// -- slimmed --       VarProxy< int > flavor_assoctrk_n;
      /// Index in trk
// -- slimmed --       VarProxy< vector<int> > flavor_assoctrk_index;
// -- slimmed --       VarProxy< float > el_dr;
// -- slimmed --       VarProxy< int > el_matched;
// -- slimmed --       VarProxy< float > mu_dr;
// -- slimmed --       VarProxy< int > mu_matched;
      /// DeltaR between the offline and trigger objects.
// -- slimmed --       VarProxy< float > L1_dr;
// -- slimmed --       VarProxy< int > L1_matched;
      /// DeltaR between the offline and trigger objects.
// -- slimmed --       VarProxy< float > L2_dr;
// -- slimmed --       VarProxy< int > L2_matched;
      /// DeltaR between the offline and trigger objects.
// -- slimmed --       VarProxy< float > EF_dr;
// -- slimmed --       VarProxy< int > EF_matched;
// -- slimmed --       VarProxy< int > bbDecision;
// -- slimmed --       VarProxy< float > SmearingFactor;


bool is_data; // ~bj 

      ClassDef( JetD3PDObjectElement, 0 )

   }; // class JetD3PDObjectElement

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-07
    *  OS   = Linux / 2.6.18-274.18.1.el5
    *  user = bjackson
    */
   class JetD3PDObject : public TObject {

   public:
      /// Constructor used when reading from a TTree
      JetD3PDObject( const ::Long64_t& master, const char* prefix = "jet_AntiKt4LCTopo_", bool is_data = true );
      /// Constructor when the object is only used for writing data out
      JetD3PDObject( const char* prefix = "jet_AntiKt4LCTopo_", bool is_data = true );

      /// Get the currently configured prefix value
      const char* GetPrefix() const;
      /// Set the prefix for the variables
      void SetPrefix( const char* prefix );

      /// Connect the object to an input TTree
      void ReadFrom( ::TTree* tree );
      /// Connect the object to an output TTree
      void WriteTo( ::TTree* tree );

      /// Turn (selected) branches either on or off
      void SetActive( ::Bool_t active = kTRUE,
                      const ::TString& pattern = ".*" );
      /// Read in all the variables that we need to write out as well
      void ReadAllActive();

      /// Clear the container. Useful when writing new branches.
      void Clear( Option_t* option = "" );
      /// Add one element to an output collection
      JetD3PDObject& Add( const JetD3PDObjectElement& el );

      /// Access a proxy class describing one element of the container
      JetD3PDObjectElement& operator[]( size_t index );
      /// Access a proxy class describing one element of the container (constant version)
      const JetD3PDObjectElement& operator[]( size_t index ) const;
      /// Add one element to an output collection
      JetD3PDObject& operator+=( const JetD3PDObjectElement& el );

      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_wpx;
      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_wpy;
      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_wet;
      VarHandle< vector<vector<unsigned int> >* > MET_Egamma10NoTau_statusWord;
      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_STVF_wpx;
      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_STVF_wpy;
      VarHandle< vector<vector<float> >* > MET_Egamma10NoTau_STVF_wet;
      VarHandle< vector<vector<unsigned int> >* > MET_Egamma10NoTau_STVF_statusWord;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_LooseEgamma10NoTau_wpx;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_LooseEgamma10NoTau_wpy;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_LooseEgamma10NoTau_wet;
// -- slimmed --       VarHandle< vector<vector<unsigned int> >* > MET_LooseEgamma10NoTau_statusWord;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_wpx;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_wpy;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_wet;
// -- slimmed --       VarHandle< vector<vector<unsigned int> >* > MET_statusWord;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_STVF_wpx;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_STVF_wpy;
// -- slimmed --       VarHandle< vector<vector<float> >* > MET_STVF_wet;
// -- slimmed --       VarHandle< vector<vector<unsigned int> >* > MET_STVF_statusWord;
      /// Number of ntuple rows.
      VarHandle< Int_t > n;
      VarHandle< vector<float>* > E;
      VarHandle< vector<float>* > pt;
      VarHandle< vector<float>* > m;
      VarHandle< vector<float>* > eta;
      VarHandle< vector<float>* > phi;
      VarHandle< vector<float>* > EtaOrigin;
      VarHandle< vector<float>* > PhiOrigin;
      VarHandle< vector<float>* > MOrigin;
      VarHandle< vector<float>* > EtaOriginEM;
      VarHandle< vector<float>* > PhiOriginEM;
      VarHandle< vector<float>* > MOriginEM;
// -- slimmed --       VarHandle< vector<float>* > WIDTH;
// -- slimmed --       VarHandle< vector<float>* > n90;
// -- slimmed --       VarHandle< vector<float>* > Timing;
      VarHandle< vector<float>* > LArQuality;
      VarHandle< vector<float>* > nTrk;
      VarHandle< vector<float>* > sumPtTrk;
      VarHandle< vector<float>* > OriginIndex;
      VarHandle< vector<float>* > HECQuality;
      VarHandle< vector<float>* > NegativeE;
      VarHandle< vector<float>* > AverageLArQF;
// -- slimmed --       VarHandle< vector<float>* > YFlip12;
// -- slimmed --       VarHandle< vector<float>* > YFlip23;
// -- slimmed --       VarHandle< vector<float>* > BCH_CORR_CELL;
// -- slimmed --       VarHandle< vector<float>* > BCH_CORR_DOTX;
// -- slimmed --       VarHandle< vector<float>* > BCH_CORR_JET;
// -- slimmed --       VarHandle< vector<float>* > BCH_CORR_JET_FORCELL;
      VarHandle< vector<float>* > ENG_BAD_CELLS;
      VarHandle< vector<float>* > N_BAD_CELLS;
      VarHandle< vector<float>* > N_BAD_CELLS_CORR;
      VarHandle< vector<float>* > BAD_CELLS_CORR_E;
// -- slimmed --       VarHandle< vector<float>* > NumTowers;
// -- slimmed --       VarHandle< vector<float>* > ootFracCells5;
// -- slimmed --       VarHandle< vector<float>* > ootFracCells10;
// -- slimmed --       VarHandle< vector<float>* > ootFracClusters5;
// -- slimmed --       VarHandle< vector<float>* > ootFracClusters10;
      VarHandle< vector<int>* > SamplingMax;
      VarHandle< vector<float>* > fracSamplingMax;
      VarHandle< vector<float>* > hecf;
// -- slimmed --       VarHandle< vector<float>* > tgap3f;
// -- slimmed --       VarHandle< vector<int>* > isUgly;
// -- slimmed --       VarHandle< vector<int>* > isBadLooseMinus;
// -- slimmed --       VarHandle< vector<int>* > isBadLoose;
// -- slimmed --       VarHandle< vector<int>* > isBadMedium;
// -- slimmed --       VarHandle< vector<int>* > isBadTight;
      VarHandle< vector<float>* > emfrac;
      VarHandle< vector<float>* > Offset;
      VarHandle< vector<float>* > EMJES;
      VarHandle< vector<float>* > EMJES_EtaCorr;
      VarHandle< vector<float>* > EMJESnooffset;
      VarHandle< vector<float>* > GCWJES;
      VarHandle< vector<float>* > GCWJES_EtaCorr;
      VarHandle< vector<float>* > CB;
      VarHandle< vector<float>* > LCJES;
      VarHandle< vector<float>* > emscale_E;
      VarHandle< vector<float>* > emscale_pt;
      VarHandle< vector<float>* > emscale_m;
      VarHandle< vector<float>* > emscale_eta;
      VarHandle< vector<float>* > emscale_phi;
      VarHandle< vector<float>* > jvtx_x;
      VarHandle< vector<float>* > jvtx_y;
      VarHandle< vector<float>* > jvtx_z;
      VarHandle< vector<float>* > jvtxf;
      VarHandle< vector<vector<float> >* > jvtxfFull;
      VarHandle< vector<float>* > GSCFactorF;
      VarHandle< vector<float>* > WidthFraction;
      VarHandle< vector<float>* > e_PreSamplerB;
// -- slimmed --       VarHandle< vector<float>* > e_EMB1;
// -- slimmed --       VarHandle< vector<float>* > e_EMB2;
// -- slimmed --       VarHandle< vector<float>* > e_EMB3;
// -- slimmed --       VarHandle< vector<float>* > e_PreSamplerE;
// -- slimmed --       VarHandle< vector<float>* > e_EME1;
// -- slimmed --       VarHandle< vector<float>* > e_EME2;
// -- slimmed --       VarHandle< vector<float>* > e_EME3;
// -- slimmed --       VarHandle< vector<float>* > e_HEC0;
// -- slimmed --       VarHandle< vector<float>* > e_HEC1;
// -- slimmed --       VarHandle< vector<float>* > e_HEC2;
// -- slimmed --       VarHandle< vector<float>* > e_HEC3;
// -- slimmed --       VarHandle< vector<float>* > e_TileBar0;
// -- slimmed --       VarHandle< vector<float>* > e_TileBar1;
// -- slimmed --       VarHandle< vector<float>* > e_TileBar2;
// -- slimmed --       VarHandle< vector<float>* > e_TileGap1;
// -- slimmed --       VarHandle< vector<float>* > e_TileGap2;
// -- slimmed --       VarHandle< vector<float>* > e_TileGap3;
// -- slimmed --       VarHandle< vector<float>* > e_TileExt0;
// -- slimmed --       VarHandle< vector<float>* > e_TileExt1;
// -- slimmed --       VarHandle< vector<float>* > e_TileExt2;
// -- slimmed --       VarHandle< vector<float>* > e_FCAL0;
// -- slimmed --       VarHandle< vector<float>* > e_FCAL1;
// -- slimmed --       VarHandle< vector<float>* > e_FCAL2;
// -- slimmed --       VarHandle< vector<int>* > Nconst;
// -- slimmed --       VarHandle< vector<vector<float> >* > ptconst_default;
// -- slimmed --       VarHandle< vector<vector<float> >* > econst_default;
// -- slimmed --       VarHandle< vector<vector<float> >* > etaconst_default;
// -- slimmed --       VarHandle< vector<vector<float> >* > phiconst_default;
// -- slimmed --       VarHandle< vector<vector<float> >* > weightconst_default;
      VarHandle< vector<float>* > constscale_E;
      VarHandle< vector<float>* > constscale_pt;
      VarHandle< vector<float>* > constscale_m;
      VarHandle< vector<float>* > constscale_eta;
      VarHandle< vector<float>* > constscale_phi;
      VarHandle< vector<float>* > flavor_weight_Comb;
      VarHandle< vector<float>* > flavor_weight_IP2D;
      VarHandle< vector<float>* > flavor_weight_IP3D;
      VarHandle< vector<float>* > flavor_weight_SV0;
      VarHandle< vector<float>* > flavor_weight_SV1;
      VarHandle< vector<float>* > flavor_weight_SV2;
      VarHandle< vector<float>* > flavor_weight_SoftMuonTagChi2;
      VarHandle< vector<float>* > flavor_weight_SecondSoftMuonTagChi2;
      VarHandle< vector<float>* > flavor_weight_JetFitterTagNN;
      VarHandle< vector<float>* > flavor_weight_JetFitterCOMBNN;
      VarHandle< vector<float>* > flavor_weight_MV1;
      VarHandle< vector<float>* > flavor_weight_MV2;
      VarHandle< vector<float>* > flavor_weight_GbbNN;
// MC only
      VarHandle< vector<int>* > flavor_truth_label;
      VarHandle< vector<float>* > flavor_truth_dRminToB;
      VarHandle< vector<float>* > flavor_truth_dRminToC;
      VarHandle< vector<float>* > flavor_truth_dRminToT;
      VarHandle< vector<int>* > flavor_truth_BHadronpdg;
      VarHandle< vector<float>* > flavor_truth_vx_x;
      VarHandle< vector<float>* > flavor_truth_vx_y;
      VarHandle< vector<float>* > flavor_truth_vx_z;
// end MC only
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_ip2d_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_ip2d_pb;
// -- slimmed --       VarHandle< vector<int>* > flavor_component_ip2d_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_ip2d_ntrk;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_ip3d_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_ip3d_pb;
// -- slimmed --       VarHandle< vector<int>* > flavor_component_ip3d_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_ip3d_ntrk;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv1_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv1_pb;
// -- slimmed --       VarHandle< vector<int>* > flavor_component_sv1_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv2_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv2_pb;
// -- slimmed --       VarHandle< vector<int>* > flavor_component_sv2_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfit_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfit_pb;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfit_pc;
// -- slimmed --       VarHandle< vector<int>* > flavor_component_jfit_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfitcomb_pu;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfitcomb_pb;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfitcomb_pc;
// -- slimmed --       VarHandle< vector<int>* > flavor_component_jfitcomb_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_jfit_nvtx;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_jfit_nvtx1t;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_jfit_ntrkAtVx;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfit_efrc;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfit_mass;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfit_sig3d;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfit_deltaPhi;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_jfit_deltaEta;
// -- slimmed --       VarHandle< vector<int>* > flavor_component_svp_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_svp_ntrkv;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_svp_ntrkj;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_svp_n2t;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_mass;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_efrc;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_x;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_y;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_z;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_err_x;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_err_y;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_err_z;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_cov_xy;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_cov_xz;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_cov_yz;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_svp_chi2;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_svp_ndof;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_svp_ntrk;
// -- slimmed --       VarHandle< vector<int>* > flavor_component_sv0p_isValid;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_sv0p_ntrkv;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_sv0p_ntrkj;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_sv0p_n2t;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_mass;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_efrc;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_x;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_y;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_z;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_err_x;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_err_y;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_err_z;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_cov_xy;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_cov_xz;
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_cov_yz;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<float>* > flavor_component_sv0p_chi2;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_sv0p_ndof;
      /// UNDOCUMENTED
// -- slimmed --       VarHandle< vector<int>* > flavor_component_sv0p_ntrk;
      /// Number of ntuple rows.
// -- slimmed --       VarHandle< vector<int>* > flavor_assoctrk_n;
      /// Index in trk
// -- slimmed --       VarHandle< vector<vector<int> >* > flavor_assoctrk_index;
// -- slimmed --       VarHandle< vector<float>* > el_dr;
// -- slimmed --       VarHandle< vector<int>* > el_matched;
// -- slimmed --       VarHandle< vector<float>* > mu_dr;
// -- slimmed --       VarHandle< vector<int>* > mu_matched;
      /// DeltaR between the offline and trigger objects.
// -- slimmed --       VarHandle< vector<float>* > L1_dr;
// -- slimmed --       VarHandle< vector<int>* > L1_matched;
      /// DeltaR between the offline and trigger objects.
// -- slimmed --       VarHandle< vector<float>* > L2_dr;
// -- slimmed --       VarHandle< vector<int>* > L2_matched;
      /// DeltaR between the offline and trigger objects.
// -- slimmed --       VarHandle< vector<float>* > EF_dr;
// -- slimmed --       VarHandle< vector<int>* > EF_matched;
// -- slimmed --       VarHandle< vector<int>* > bbDecision;
// -- slimmed --       VarHandle< vector<float>* > SmearingFactor;

   private:
      mutable std::vector< JetD3PDObjectElement > fProxies; ///< Internal list of proxy objects
      std::map< ::TString, VarHandleBase* > fHandles; ///< Book-keeper of the VarHandle members
      const ::Bool_t fFromInput; ///< Flag specifying if object is used for D3PD reading
      const ::TString fPrefix; ///< Prefix to the branch names


bool is_data; // ~bj 

      ClassDef( JetD3PDObject, 0 )

   }; // class JetD3PDObject

} // namespace D3PDReader

#endif // D3PDREADER_JetD3PDObject_H
