// Dear emacs, this is -*- c++ -*-
// -------------------------------------------------------------
//             Code produced by D3PDMakerReader
//
//  author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
// -------------------------------------------------------------
#ifndef D3PDREADER_METD3PDObject_H
#define D3PDREADER_METD3PDObject_H

#include <map>

#include <TObject.h>
#include <TString.h>

#include "VarHandle.h"

class TTree;

namespace D3PDReader {

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-07
    *  OS   = Linux / 2.6.18-274.18.1.el5
    *  user = bjackson
    */
   class METD3PDObject : public TObject {

   public:
      /// Constructor used when reading from a TTree
      METD3PDObject( const ::Long64_t& master, const char* prefix = "MET_Egamma10NoTau_", bool is_data = true );
      /// Constructor when the object is only used for writing data out
      METD3PDObject( const char* prefix = "MET_Egamma10NoTau_", bool is_data = true );

      /// Get the currently configured prefix value
      const char* GetPrefix() const;
      /// Set the prefix for the variables
      void SetPrefix( const char* prefix );

      /// Connect the object to an input TTree
      void ReadFrom( ::TTree* tree );
      /// Connect the object to an output TTree
      void WriteTo( ::TTree* tree );

      /// Turn (selected) branches either on or off
      void SetActive( ::Bool_t active = kTRUE,
                      const ::TString& pattern = ".*" );
      /// Read in all the variables that we need to write out as well
      void ReadAllActive();

      VarHandle< Float_t > RefGamma_etx;
      VarHandle< Float_t > RefGamma_ety;
      VarHandle< Float_t > RefGamma_sumet;
      VarHandle< Float_t > RefJet_etx;
      VarHandle< Float_t > RefJet_ety;
      VarHandle< Float_t > RefJet_sumet;
      VarHandle< Float_t > CellOut_etx;
      VarHandle< Float_t > CellOut_ety;
      VarHandle< Float_t > CellOut_sumet;
      VarHandle< Float_t > Track_etx;
      VarHandle< Float_t > Track_ety;
      VarHandle< Float_t > Track_sumet;
      VarHandle< Float_t > SoftJets_etx;
      VarHandle< Float_t > SoftJets_ety;
      VarHandle< Float_t > SoftJets_sumet;
      VarHandle< Float_t > RefMuon_etx;
      VarHandle< Float_t > RefMuon_ety;
      VarHandle< Float_t > RefMuon_sumet;

   private:
      std::map< ::TString, VarHandleBase* > fHandles; ///< Book-keeper of the VarHandle members
      const ::Bool_t fFromInput; ///< Flag specifying if object is used for D3PD reading
      const ::TString fPrefix; ///< Prefix to the branch names


bool is_data; // ~bj 

      ClassDef( METD3PDObject, 0 )

   }; // class METD3PDObject

} // namespace D3PDReader

#endif // D3PDREADER_METD3PDObject_H
