// Dear emacs, this is -*- c++ -*-
// -------------------------------------------------------------
//             Code produced by D3PDMakerReader
//
//  author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
// -------------------------------------------------------------
#ifndef D3PDREADER_TriggerVecD3PDObject_H
#define D3PDREADER_TriggerVecD3PDObject_H

#include <map>
#include <vector>
using std::vector;

#include <TObject.h>
#include <TString.h>

#include "VarHandle.h"
#include "VarProxy.h"

class TTree;

namespace D3PDReader {

   // Forward declaration(s):
   class TriggerVecD3PDObject;

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-07
    *  OS   = Linux / 2.6.18-274.18.1.el5
    *  user = bjackson
    */
   class TriggerVecD3PDObjectElement : public TObject {

      friend class TriggerVecD3PDObject;

   protected:
      /// Constructor only visible to TriggerVecD3PDObject
      TriggerVecD3PDObjectElement( size_t index, const TriggerVecD3PDObject& parent );

   public:
      /// Copy constructor
      TriggerVecD3PDObjectElement( const TriggerVecD3PDObjectElement& parent );

      /// Did this object pass the chain EF_2e12Tvh_loose1
      VarProxy< int > trig_EF_el_EF_2e12Tvh_loose1;
      /// Did this object pass the chain EF_2e5_tight1_Jpsi
      VarProxy< int > trig_EF_el_EF_2e5_tight1_Jpsi;
      /// Did this object pass the chain EF_2e7T_loose1_mu6
      VarProxy< int > trig_EF_el_EF_2e7T_loose1_mu6;
      /// Did this object pass the chain EF_2e7T_medium1_mu6
      VarProxy< int > trig_EF_el_EF_2e7T_medium1_mu6;
      /// Did this object pass the chain EF_e11_etcut
      VarProxy< int > trig_EF_el_EF_e11_etcut;
      /// Did this object pass the chain EF_e12Tvh_loose1
      VarProxy< int > trig_EF_el_EF_e12Tvh_loose1;
      /// Did this object pass the chain EF_e12Tvh_medium1
      VarProxy< int > trig_EF_el_EF_e12Tvh_medium1;
      /// Did this object pass the chain EF_e12Tvh_medium1_mu6_topo_medium
      VarProxy< int > trig_EF_el_EF_e12Tvh_medium1_mu6_topo_medium;
      /// Did this object pass the chain EF_e12Tvh_medium1_mu8
      VarProxy< int > trig_EF_el_EF_e12Tvh_medium1_mu8;
      /// Did this object pass the chain EF_e13_etcutTrk_xs60
      VarProxy< int > trig_EF_el_EF_e13_etcutTrk_xs60;
      /// Did this object pass the chain EF_e13_etcutTrk_xs60_dphi2j15xe20
      VarProxy< int > trig_EF_el_EF_e13_etcutTrk_xs60_dphi2j15xe20;
      /// Did this object pass the chain EF_e14_tight1_e4_etcut_Jpsi
      VarProxy< int > trig_EF_el_EF_e14_tight1_e4_etcut_Jpsi;
      /// Did this object pass the chain EF_e15vh_medium1
      VarProxy< int > trig_EF_el_EF_e15vh_medium1;
      /// Did this object pass the chain EF_e18_loose1
      VarProxy< int > trig_EF_el_EF_e18_loose1;
      /// Did this object pass the chain EF_e18_loose1_g25_medium
      VarProxy< int > trig_EF_el_EF_e18_loose1_g25_medium;
      /// Did this object pass the chain EF_e18_medium1
      VarProxy< int > trig_EF_el_EF_e18_medium1;
      /// Did this object pass the chain EF_e18_medium1_g25_loose
      VarProxy< int > trig_EF_el_EF_e18_medium1_g25_loose;
      /// Did this object pass the chain EF_e18vh_medium1
      VarProxy< int > trig_EF_el_EF_e18vh_medium1;
      /// Did this object pass the chain EF_e18vh_medium1_2e7T_medium1
      VarProxy< int > trig_EF_el_EF_e18vh_medium1_2e7T_medium1;
      /// Did this object pass the chain EF_e20_etcutTrk_xe30_dphi2j15xe20
      VarProxy< int > trig_EF_el_EF_e20_etcutTrk_xe30_dphi2j15xe20;
      /// Did this object pass the chain EF_e20_etcutTrk_xs60_dphi2j15xe20
      VarProxy< int > trig_EF_el_EF_e20_etcutTrk_xs60_dphi2j15xe20;
      /// Did this object pass the chain EF_e20vhT_medium1_g6T_etcut_Upsi
      VarProxy< int > trig_EF_el_EF_e20vhT_medium1_g6T_etcut_Upsi;
      /// Did this object pass the chain EF_e20vhT_tight1_g6T_etcut_Upsi
      VarProxy< int > trig_EF_el_EF_e20vhT_tight1_g6T_etcut_Upsi;
      /// Did this object pass the chain EF_e22vh_loose
      VarProxy< int > trig_EF_el_EF_e22vh_loose;
      /// Did this object pass the chain EF_e22vh_loose0
      VarProxy< int > trig_EF_el_EF_e22vh_loose0;
      /// Did this object pass the chain EF_e22vh_loose1
      VarProxy< int > trig_EF_el_EF_e22vh_loose1;
      /// Did this object pass the chain EF_e22vh_medium1
      VarProxy< int > trig_EF_el_EF_e22vh_medium1;
      /// Did this object pass the chain EF_e22vh_medium1_IDTrkNoCut
      VarProxy< int > trig_EF_el_EF_e22vh_medium1_IDTrkNoCut;
      /// Did this object pass the chain EF_e22vhi_medium1
      VarProxy< int > trig_EF_el_EF_e22vhi_medium1;
      /// Did this object pass the chain EF_e24vh_loose
      VarProxy< int > trig_EF_el_EF_e24vh_loose;
      /// Did this object pass the chain EF_e24vh_loose0
      VarProxy< int > trig_EF_el_EF_e24vh_loose0;
      /// Did this object pass the chain EF_e24vh_loose1
      VarProxy< int > trig_EF_el_EF_e24vh_loose1;
      /// Did this object pass the chain EF_e24vh_medium1
      VarProxy< int > trig_EF_el_EF_e24vh_medium1;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe30
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_EFxe30;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe30_tcem
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_EFxe30_tcem;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe35_tcem
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_EFxe35_tcem;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe35_tclcw
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_EFxe35_tclcw;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe40
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_EFxe40;
      /// Did this object pass the chain EF_e24vh_medium1_IDTrkNoCut
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_IDTrkNoCut;
      /// Did this object pass the chain EF_e24vh_medium1_IdScan
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_IdScan;
      /// Did this object pass the chain EF_e24vh_medium1_L2StarB
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_L2StarB;
      /// Did this object pass the chain EF_e24vh_medium1_L2StarC
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_L2StarC;
      /// Did this object pass the chain EF_e24vh_medium1_SiTrk
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_SiTrk;
      /// Did this object pass the chain EF_e24vh_medium1_TRT
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_TRT;
      /// Did this object pass the chain EF_e24vh_medium1_b35_mediumEF_j35_a4tchad
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_b35_mediumEF_j35_a4tchad;
      /// Did this object pass the chain EF_e24vh_medium1_e7_medium1
      VarProxy< int > trig_EF_el_EF_e24vh_medium1_e7_medium1;
      /// Did this object pass the chain EF_e24vh_tight1_e15_NoCut_Zee
      VarProxy< int > trig_EF_el_EF_e24vh_tight1_e15_NoCut_Zee;
      /// Did this object pass the chain EF_e24vhi_loose1_mu8
      VarProxy< int > trig_EF_el_EF_e24vhi_loose1_mu8;
      /// Did this object pass the chain EF_e24vhi_medium1
      VarProxy< int > trig_EF_el_EF_e24vhi_medium1;
      /// Did this object pass the chain EF_e45_medium1
      VarProxy< int > trig_EF_el_EF_e45_medium1;
      /// Did this object pass the chain EF_e5_tight1
      VarProxy< int > trig_EF_el_EF_e5_tight1;
      /// Did this object pass the chain EF_e5_tight1_e14_etcut_Jpsi
      VarProxy< int > trig_EF_el_EF_e5_tight1_e14_etcut_Jpsi;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi
      VarProxy< int > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_L2StarB
      VarProxy< int > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_L2StarB;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_L2StarC
      VarProxy< int > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_L2StarC;
      /// Did this object pass the chain EF_e5_tight1_e5_NoCut
      VarProxy< int > trig_EF_el_EF_e5_tight1_e5_NoCut;
      /// Did this object pass the chain EF_e5_tight1_e9_etcut_Jpsi
      VarProxy< int > trig_EF_el_EF_e5_tight1_e9_etcut_Jpsi;
      /// Did this object pass the chain EF_e60_medium1
      VarProxy< int > trig_EF_el_EF_e60_medium1;
      /// Did this object pass the chain EF_e7T_loose1
      VarProxy< int > trig_EF_el_EF_e7T_loose1;
      /// Did this object pass the chain EF_e7T_loose1_2mu6
      VarProxy< int > trig_EF_el_EF_e7T_loose1_2mu6;
      /// Did this object pass the chain EF_e7T_medium1
      VarProxy< int > trig_EF_el_EF_e7T_medium1;
      /// Did this object pass the chain EF_e7T_medium1_2mu6
      VarProxy< int > trig_EF_el_EF_e7T_medium1_2mu6;
      /// Did this object pass the chain EF_e9_tight1_e4_etcut_Jpsi
      VarProxy< int > trig_EF_el_EF_e9_tight1_e4_etcut_Jpsi;
      /// Did this object pass the chain EF_eb_physics
      VarProxy< int > trig_EF_el_EF_eb_physics;
      /// Did this object pass the chain EF_eb_physics_empty
      VarProxy< int > trig_EF_el_EF_eb_physics_empty;
      /// Did this object pass the chain EF_eb_physics_firstempty
      VarProxy< int > trig_EF_el_EF_eb_physics_firstempty;
      /// Did this object pass the chain EF_eb_physics_noL1PS
      VarProxy< int > trig_EF_el_EF_eb_physics_noL1PS;
      /// Did this object pass the chain EF_eb_physics_unpaired_iso
      VarProxy< int > trig_EF_el_EF_eb_physics_unpaired_iso;
      /// Did this object pass the chain EF_eb_physics_unpaired_noniso
      VarProxy< int > trig_EF_el_EF_eb_physics_unpaired_noniso;
      /// Did this object pass the chain EF_eb_random
      VarProxy< int > trig_EF_el_EF_eb_random;
      /// Did this object pass the chain EF_eb_random_empty
      VarProxy< int > trig_EF_el_EF_eb_random_empty;
      /// Did this object pass the chain EF_eb_random_firstempty
      VarProxy< int > trig_EF_el_EF_eb_random_firstempty;
      /// Did this object pass the chain EF_eb_random_unpaired_iso
      VarProxy< int > trig_EF_el_EF_eb_random_unpaired_iso;
      VarProxy< float > trig_EF_emcl_pt;
      VarProxy< float > trig_EF_emcl_eta;
      VarProxy< float > trig_EF_emcl_phi;
      VarProxy< float > trig_EF_emcl_E_em;
      VarProxy< float > trig_EF_emcl_E_had;
      VarProxy< float > trig_EF_emcl_slw_pt;
      VarProxy< float > trig_EF_emcl_slw_eta;
      VarProxy< float > trig_EF_emcl_slw_phi;
      VarProxy< float > trig_EF_emcl_slw_E_em;
      VarProxy< float > trig_EF_emcl_slw_E_had;
      VarProxy< float > trig_EF_el_E;
      VarProxy< float > trig_EF_el_Et;
      VarProxy< float > trig_EF_el_pt;
      VarProxy< float > trig_EF_el_m;
      VarProxy< float > trig_EF_el_eta;
      VarProxy< float > trig_EF_el_phi;
      VarProxy< float > trig_EF_el_px;
      VarProxy< float > trig_EF_el_py;
      VarProxy< float > trig_EF_el_pz;
      VarProxy< float > trig_EF_el_charge;
      VarProxy< int > trig_EF_el_author;
      /// IsEM mask --- bits are set for each cut that FAILS.
      VarProxy< unsigned int > trig_EF_el_isEM;
      /// Loose IsEM mask --- bits are set for each cut that FAILS.
      VarProxy< unsigned int > trig_EF_el_isEMLoose;
      /// Medium IsEM mask --- bits are set for each cut that FAILS.
      VarProxy< unsigned int > trig_EF_el_isEMMedium;
      /// Tight IsEM mask --- bits are set for each cut that FAILS.
      VarProxy< unsigned int > trig_EF_el_isEMTight;
      VarProxy< int > trig_EF_el_loose;
      VarProxy< int > trig_EF_el_looseIso;
      VarProxy< int > trig_EF_el_medium;
      VarProxy< int > trig_EF_el_mediumIso;
      VarProxy< int > trig_EF_el_mediumWithoutTrack;
      VarProxy< int > trig_EF_el_mediumIsoWithoutTrack;
      VarProxy< int > trig_EF_el_tight;
      VarProxy< int > trig_EF_el_tightIso;
      VarProxy< int > trig_EF_el_tightWithoutTrack;
      VarProxy< int > trig_EF_el_tightIsoWithoutTrack;
      VarProxy< int > trig_EF_el_loosePP;
      VarProxy< int > trig_EF_el_loosePPIso;
      VarProxy< int > trig_EF_el_mediumPP;
      VarProxy< int > trig_EF_el_mediumPPIso;
      VarProxy< int > trig_EF_el_tightPP;
      VarProxy< int > trig_EF_el_tightPPIso;
      VarProxy< float > trig_EF_el_vertweight;
      VarProxy< int > trig_EF_el_hastrack;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_CB_pt;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_CB_eta;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_CB_phi;
      VarProxy< vector<int> > trig_EF_trigmuonef_track_CB_hasCB;

      // =============================================================================
      // = Data only
      // =============================================================================
      /// Did this object pass the chain EF_2mu10
      VarProxy< int > trig_EF_trigmuonef_EF_2mu10;
      /// Did this object pass the chain EF_2mu10_MSonly_g10_loose
      VarProxy< int > trig_EF_trigmuonef_EF_2mu10_MSonly_g10_loose;
      /// Did this object pass the chain EF_2mu13
      VarProxy< int > trig_EF_trigmuonef_EF_2mu13;
      /// Did this object pass the chain EF_2mu13_Zmumu_IDTrkNoCut
      VarProxy< int > trig_EF_trigmuonef_EF_2mu13_Zmumu_IDTrkNoCut;
      /// Did this object pass the chain EF_2mu13_l2muonSA
      VarProxy< int > trig_EF_trigmuonef_EF_2mu13_l2muonSA;
      /// Did this object pass the chain EF_2mu15
      VarProxy< int > trig_EF_trigmuonef_EF_2mu15;
      /// Did this object pass the chain EF_2mu4T
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T;
      /// Did this object pass the chain EF_2mu4T_2e5_tight1
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_2e5_tight1;
      /// Did this object pass the chain EF_2mu4T_Bmumu
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Bmumu;
      /// Did this object pass the chain EF_2mu4T_Bmumu_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Bmumu_Barrel;
      /// Did this object pass the chain EF_2mu4T_Bmumu_BarrelOnly
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Bmumu_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_Bmumux
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Bmumux;
      /// Did this object pass the chain EF_2mu4T_Bmumux_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Bmumux_Barrel;
      /// Did this object pass the chain EF_2mu4T_Bmumux_BarrelOnly
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Bmumux_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_DiMu
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_DiMu;
      /// Did this object pass the chain EF_2mu4T_DiMu_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_DiMu_Barrel;
      /// Did this object pass the chain EF_2mu4T_DiMu_BarrelOnly
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_DiMu_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_DiMu_L2StarB
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_DiMu_L2StarB;
      /// Did this object pass the chain EF_2mu4T_DiMu_L2StarC
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_DiMu_L2StarC;
      /// Did this object pass the chain EF_2mu4T_DiMu_e5_tight1
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_DiMu_e5_tight1;
      /// Did this object pass the chain EF_2mu4T_DiMu_l2muonSA
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_DiMu_l2muonSA;
      /// Did this object pass the chain EF_2mu4T_DiMu_noVtx_noOS
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_DiMu_noVtx_noOS;
      /// Did this object pass the chain EF_2mu4T_Jpsimumu
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Jpsimumu;
      /// Did this object pass the chain EF_2mu4T_Jpsimumu_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Jpsimumu_Barrel;
      /// Did this object pass the chain EF_2mu4T_Jpsimumu_BarrelOnly
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Jpsimumu_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_Jpsimumu_IDTrkNoCut
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Jpsimumu_IDTrkNoCut;
      /// Did this object pass the chain EF_2mu4T_Upsimumu
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Upsimumu;
      /// Did this object pass the chain EF_2mu4T_Upsimumu_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Upsimumu_Barrel;
      /// Did this object pass the chain EF_2mu4T_Upsimumu_BarrelOnly
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_Upsimumu_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_xe60
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_xe60;
      /// Did this object pass the chain EF_2mu4T_xe60_tclcw
      VarProxy< int > trig_EF_trigmuonef_EF_2mu4T_xe60_tclcw;
      /// Did this object pass the chain EF_2mu6
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6;
      /// Did this object pass the chain EF_2mu6_Bmumu
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6_Bmumu;
      /// Did this object pass the chain EF_2mu6_Bmumux
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6_Bmumux;
      /// Did this object pass the chain EF_2mu6_DiMu
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6_DiMu;
      /// Did this object pass the chain EF_2mu6_DiMu_DY20
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6_DiMu_DY20;
      /// Did this object pass the chain EF_2mu6_DiMu_DY25
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6_DiMu_DY25;
      /// Did this object pass the chain EF_2mu6_DiMu_noVtx_noOS
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6_DiMu_noVtx_noOS;
      /// Did this object pass the chain EF_2mu6_Jpsimumu
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6_Jpsimumu;
      /// Did this object pass the chain EF_2mu6_Upsimumu
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6_Upsimumu;
      /// Did this object pass the chain EF_2mu6i_DiMu_DY
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6i_DiMu_DY;
      /// Did this object pass the chain EF_2mu6i_DiMu_DY_2j25_a4tchad
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6i_DiMu_DY_2j25_a4tchad;
      /// Did this object pass the chain EF_2mu6i_DiMu_DY_noVtx_noOS
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6i_DiMu_DY_noVtx_noOS;
      /// Did this object pass the chain EF_2mu6i_DiMu_DY_noVtx_noOS_2j25_a4tchad
      VarProxy< int > trig_EF_trigmuonef_EF_2mu6i_DiMu_DY_noVtx_noOS_2j25_a4tchad;
      /// Did this object pass the chain EF_2mu8_EFxe30
      VarProxy< int > trig_EF_trigmuonef_EF_2mu8_EFxe30;
      /// Did this object pass the chain EF_2mu8_EFxe30_tclcw
      VarProxy< int > trig_EF_trigmuonef_EF_2mu8_EFxe30_tclcw;
      /// Did this object pass the chain EF_mu10
      VarProxy< int > trig_EF_trigmuonef_EF_mu10;
      /// Did this object pass the chain EF_mu10_Jpsimumu
      VarProxy< int > trig_EF_trigmuonef_EF_mu10_Jpsimumu;
      /// Did this object pass the chain EF_mu10_MSonly
      VarProxy< int > trig_EF_trigmuonef_EF_mu10_MSonly;
      /// Did this object pass the chain EF_mu10_Upsimumu_tight_FS
      VarProxy< int > trig_EF_trigmuonef_EF_mu10_Upsimumu_tight_FS;
      /// Did this object pass the chain EF_mu10i_g10_medium
      VarProxy< int > trig_EF_trigmuonef_EF_mu10i_g10_medium;
      /// Did this object pass the chain EF_mu10i_g10_medium_TauMass
      VarProxy< int > trig_EF_trigmuonef_EF_mu10i_g10_medium_TauMass;
      /// Did this object pass the chain EF_mu10i_loose_g12Tvh_medium
      VarProxy< int > trig_EF_trigmuonef_EF_mu10i_loose_g12Tvh_medium;
      /// Did this object pass the chain EF_mu10i_loose_g12Tvh_medium_TauMass
      VarProxy< int > trig_EF_trigmuonef_EF_mu10i_loose_g12Tvh_medium_TauMass;
      /// Did this object pass the chain EF_mu11_empty_NoAlg
      VarProxy< int > trig_EF_trigmuonef_EF_mu11_empty_NoAlg;
      /// Did this object pass the chain EF_mu13
      VarProxy< int > trig_EF_trigmuonef_EF_mu13;
      /// Did this object pass the chain EF_mu15
      VarProxy< int > trig_EF_trigmuonef_EF_mu15;
      /// Did this object pass the chain EF_mu18
      VarProxy< int > trig_EF_trigmuonef_EF_mu18;
      /// Did this object pass the chain EF_mu18_2g10_loose
      VarProxy< int > trig_EF_trigmuonef_EF_mu18_2g10_loose;
      /// Did this object pass the chain EF_mu18_2g10_medium
      VarProxy< int > trig_EF_trigmuonef_EF_mu18_2g10_medium;
      /// Did this object pass the chain EF_mu18_IDTrkNoCut_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu18_IDTrkNoCut_tight;
      /// Did this object pass the chain EF_mu18_medium
      VarProxy< int > trig_EF_trigmuonef_EF_mu18_medium;
      /// Did this object pass the chain EF_mu18_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu18_tight;
      /// Did this object pass the chain EF_mu18_tight_2mu4_EFFS
      VarProxy< int > trig_EF_trigmuonef_EF_mu18_tight_2mu4_EFFS;
      /// Did this object pass the chain EF_mu18_tight_e7_medium1
      VarProxy< int > trig_EF_trigmuonef_EF_mu18_tight_e7_medium1;
      /// Did this object pass the chain EF_mu18_tight_mu8_EFFS
      VarProxy< int > trig_EF_trigmuonef_EF_mu18_tight_mu8_EFFS;
      /// Did this object pass the chain EF_mu18i4_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu18i4_tight;
      /// Did this object pass the chain EF_mu20i_tight_g5_loose_TauMass
      VarProxy< int > trig_EF_trigmuonef_EF_mu20i_tight_g5_loose_TauMass;
      /// Did this object pass the chain EF_mu20i_tight_g5_medium
      VarProxy< int > trig_EF_trigmuonef_EF_mu20i_tight_g5_medium;
      /// Did this object pass the chain EF_mu20i_tight_g5_medium_TauMass
      VarProxy< int > trig_EF_trigmuonef_EF_mu20i_tight_g5_medium_TauMass;
      /// Did this object pass the chain EF_mu20it_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu20it_tight;
      /// Did this object pass the chain EF_mu22_IDTrkNoCut_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu22_IDTrkNoCut_tight;
      /// Did this object pass the chain EF_mu24
      VarProxy< int > trig_EF_trigmuonef_EF_mu24;
      /// Did this object pass the chain EF_mu24_g20vh_loose
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_g20vh_loose;
      /// Did this object pass the chain EF_mu24_g20vh_medium
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_g20vh_medium;
      /// Did this object pass the chain EF_mu24_j65_a4tchad
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_j65_a4tchad;
      /// Did this object pass the chain EF_mu24_j65_a4tchad_EFxe40
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_j65_a4tchad_EFxe40;
      /// Did this object pass the chain EF_mu24_j65_a4tchad_EFxe40_tclcw
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_j65_a4tchad_EFxe40_tclcw;
      /// Did this object pass the chain EF_mu24_j65_a4tchad_EFxe60_tclcw
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_j65_a4tchad_EFxe60_tclcw;
      /// Did this object pass the chain EF_mu24_medium
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_medium;
      /// Did this object pass the chain EF_mu24_muCombTag_NoEF_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_muCombTag_NoEF_tight;
      /// Did this object pass the chain EF_mu24_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight;
      /// Did this object pass the chain EF_mu24_tight_3j35_a4tchad
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight_3j35_a4tchad;
      /// Did this object pass the chain EF_mu24_tight_EFxe40
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight_EFxe40;
      /// Did this object pass the chain EF_mu24_tight_L2StarB
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight_L2StarB;
      /// Did this object pass the chain EF_mu24_tight_L2StarC
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight_L2StarC;
      /// Did this object pass the chain EF_mu24_tight_MG
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight_MG;
      /// Did this object pass the chain EF_mu24_tight_MuonEF
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight_MuonEF;
      /// Did this object pass the chain EF_mu24_tight_b35_mediumEF_j35_a4tchad
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight_b35_mediumEF_j35_a4tchad;
      /// Did this object pass the chain EF_mu24_tight_mu6_EFFS
      VarProxy< int > trig_EF_trigmuonef_EF_mu24_tight_mu6_EFFS;
      /// Did this object pass the chain EF_mu24i_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu24i_tight;
      /// Did this object pass the chain EF_mu24i_tight_MG
      VarProxy< int > trig_EF_trigmuonef_EF_mu24i_tight_MG;
      /// Did this object pass the chain EF_mu24i_tight_MuonEF
      VarProxy< int > trig_EF_trigmuonef_EF_mu24i_tight_MuonEF;
      /// Did this object pass the chain EF_mu24i_tight_l2muonSA
      VarProxy< int > trig_EF_trigmuonef_EF_mu24i_tight_l2muonSA;
      /// Did this object pass the chain EF_mu36_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu36_tight;
      /// Did this object pass the chain EF_mu40_MSonly_barrel_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu40_MSonly_barrel_tight;
      /// Did this object pass the chain EF_mu40_muCombTag_NoEF
      VarProxy< int > trig_EF_trigmuonef_EF_mu40_muCombTag_NoEF;
      /// Did this object pass the chain EF_mu40_slow_outOfTime_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu40_slow_outOfTime_tight;
      /// Did this object pass the chain EF_mu40_slow_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu40_slow_tight;
      /// Did this object pass the chain EF_mu40_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu40_tight;
      /// Did this object pass the chain EF_mu4T
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T;
      /// Did this object pass the chain EF_mu4T_cosmic
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_cosmic;
      /// Did this object pass the chain EF_mu4T_j110_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j110_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j110_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j110_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j145_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j145_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j145_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j145_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j15_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j15_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j15_a4tchad_matchedZ
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j15_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j180_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j180_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j180_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j180_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j220_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j220_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j220_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j220_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j25_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j25_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j25_a4tchad_matchedZ
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j25_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j280_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j280_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j280_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j280_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j35_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j35_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j35_a4tchad_matchedZ
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j35_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j45_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j45_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j45_a4tchad_L2FS_matchedZ
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j45_a4tchad_L2FS_matchedZ;
      /// Did this object pass the chain EF_mu4T_j45_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j45_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j45_a4tchad_matchedZ
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j45_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j55_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j55_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j55_a4tchad_L2FS_matchedZ
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j55_a4tchad_L2FS_matchedZ;
      /// Did this object pass the chain EF_mu4T_j55_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j55_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j55_a4tchad_matchedZ
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j55_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j65_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j65_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j65_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j65_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j65_a4tchad_xe60_tclcw_loose
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j65_a4tchad_xe60_tclcw_loose;
      /// Did this object pass the chain EF_mu4T_j65_a4tchad_xe70_tclcw_veryloose
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j65_a4tchad_xe70_tclcw_veryloose;
      /// Did this object pass the chain EF_mu4T_j80_a4tchad_L2FS_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j80_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j80_a4tchad_matched
      VarProxy< int > trig_EF_trigmuonef_EF_mu4T_j80_a4tchad_matched;
      /// Did this object pass the chain EF_mu4Ti_g20Tvh_medium
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Ti_g20Tvh_medium;
      /// Did this object pass the chain EF_mu4Ti_g20Tvh_medium_TauMass
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Ti_g20Tvh_medium_TauMass;
      /// Did this object pass the chain EF_mu4Tmu6_Bmumu
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Bmumu;
      /// Did this object pass the chain EF_mu4Tmu6_Bmumu_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Bmumu_Barrel;
      /// Did this object pass the chain EF_mu4Tmu6_Bmumux
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Bmumux;
      /// Did this object pass the chain EF_mu4Tmu6_Bmumux_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Bmumux_Barrel;
      /// Did this object pass the chain EF_mu4Tmu6_DiMu
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_DiMu;
      /// Did this object pass the chain EF_mu4Tmu6_DiMu_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_DiMu_Barrel;
      /// Did this object pass the chain EF_mu4Tmu6_DiMu_noVtx_noOS
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_DiMu_noVtx_noOS;
      /// Did this object pass the chain EF_mu4Tmu6_Jpsimumu
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Jpsimumu;
      /// Did this object pass the chain EF_mu4Tmu6_Jpsimumu_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Jpsimumu_Barrel;
      /// Did this object pass the chain EF_mu4Tmu6_Jpsimumu_IDTrkNoCut
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Jpsimumu_IDTrkNoCut;
      /// Did this object pass the chain EF_mu4Tmu6_Upsimumu
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Upsimumu;
      /// Did this object pass the chain EF_mu4Tmu6_Upsimumu_Barrel
      VarProxy< int > trig_EF_trigmuonef_EF_mu4Tmu6_Upsimumu_Barrel;
      /// Did this object pass the chain EF_mu4_L1MU11_MSonly_cosmic
      VarProxy< int > trig_EF_trigmuonef_EF_mu4_L1MU11_MSonly_cosmic;
      /// Did this object pass the chain EF_mu4_L1MU11_cosmic
      VarProxy< int > trig_EF_trigmuonef_EF_mu4_L1MU11_cosmic;
      /// Did this object pass the chain EF_mu4_empty_NoAlg
      VarProxy< int > trig_EF_trigmuonef_EF_mu4_empty_NoAlg;
      /// Did this object pass the chain EF_mu4_firstempty_NoAlg
      VarProxy< int > trig_EF_trigmuonef_EF_mu4_firstempty_NoAlg;
      /// Did this object pass the chain EF_mu4_unpaired_iso_NoAlg
      VarProxy< int > trig_EF_trigmuonef_EF_mu4_unpaired_iso_NoAlg;
      /// Did this object pass the chain EF_mu50_MSonly_barrel_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu50_MSonly_barrel_tight;
      /// Did this object pass the chain EF_mu6
      VarProxy< int > trig_EF_trigmuonef_EF_mu6;
      /// Did this object pass the chain EF_mu60_slow_outOfTime_tight1
      VarProxy< int > trig_EF_trigmuonef_EF_mu60_slow_outOfTime_tight1;
      /// Did this object pass the chain EF_mu60_slow_tight1
      VarProxy< int > trig_EF_trigmuonef_EF_mu60_slow_tight1;
      /// Did this object pass the chain EF_mu6_Jpsimumu_tight
      VarProxy< int > trig_EF_trigmuonef_EF_mu6_Jpsimumu_tight;
      /// Did this object pass the chain EF_mu6_MSonly
      VarProxy< int > trig_EF_trigmuonef_EF_mu6_MSonly;
      /// Did this object pass the chain EF_mu6_Trk_Jpsi_loose
      VarProxy< int > trig_EF_trigmuonef_EF_mu6_Trk_Jpsi_loose;
      /// Did this object pass the chain EF_mu8
      VarProxy< int > trig_EF_trigmuonef_EF_mu8;
      /// Did this object pass the chain EF_mu8_4j45_a4tchad_L2FS
      VarProxy< int > trig_EF_trigmuonef_EF_mu8_4j45_a4tchad_L2FS;
      VarProxy< vector<int> > trig_EF_trigmuonef_track_MuonType;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_MS_pt;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_MS_eta;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_MS_phi;
      VarProxy< vector<int> > trig_EF_trigmuonef_track_MS_hasMS;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_SA_pt;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_SA_eta;
      VarProxy< vector<float> > trig_EF_trigmuonef_track_SA_phi;
      VarProxy< vector<int> > trig_EF_trigmuonef_track_SA_hasSA;
      
      // =============================================================================
      // = MC only
      // =============================================================================
      /// Did this object pass the chain EF_e12Tvh_loose1_mu8
      VarProxy< int > trig_EF_el_EF_e12Tvh_loose1_mu8;
      /// Did this object pass the chain EF_e12Tvh_medium1_mu10
      VarProxy< int > trig_EF_el_EF_e12Tvh_medium1_mu10;
      /// Did this object pass the chain EF_e12Tvh_medium1_mu6
      VarProxy< int > trig_EF_el_EF_e12Tvh_medium1_mu6;
      /// Did this object pass the chain EF_e18_loose1_g35_loose
      VarProxy< int > trig_EF_el_EF_e18_loose1_g35_loose;
      /// Did this object pass the chain EF_e18_loose1_g35_medium
      VarProxy< int > trig_EF_el_EF_e18_loose1_g35_medium;
      /// Did this object pass the chain EF_e18_medium1_g25_medium
      VarProxy< int > trig_EF_el_EF_e18_medium1_g25_medium;
      /// Did this object pass the chain EF_e18_medium1_g35_loose
      VarProxy< int > trig_EF_el_EF_e18_medium1_g35_loose;
      /// Did this object pass the chain EF_e18_medium1_g35_medium
      VarProxy< int > trig_EF_el_EF_e18_medium1_g35_medium;
      /// Did this object pass the chain EF_e22vh_medium1_IdScan
      VarProxy< int > trig_EF_el_EF_e22vh_medium1_IdScan;
      /// Did this object pass the chain EF_e22vh_medium1_SiTrk
      VarProxy< int > trig_EF_el_EF_e22vh_medium1_SiTrk;
      /// Did this object pass the chain EF_e22vh_medium1_TRT
      VarProxy< int > trig_EF_el_EF_e22vh_medium1_TRT;
      /// Did this object pass the chain EF_e45_etcut
      VarProxy< int > trig_EF_el_EF_e45_etcut;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_IdScan
      VarProxy< int > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_IdScan;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_SiTrk
      VarProxy< int > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_SiTrk;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_TRT
      VarProxy< int > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_TRT;
      /// Did this object pass the chain EF_e60_etcut
      VarProxy< int > trig_EF_el_EF_e60_etcut;
      

      ClassDef( TriggerVecD3PDObjectElement, 0 )

   }; // class TriggerVecD3PDObjectElement

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-07
    *  OS   = Linux / 2.6.18-274.18.1.el5
    *  user = bjackson
    */
   class TriggerVecD3PDObject : public TObject {

   public:
      /// Constructor used when reading from a TTree
      TriggerVecD3PDObject( const ::Long64_t& master, const char* prefix = "" );
      /// Constructor when the object is only used for writing data out
      TriggerVecD3PDObject( const char* prefix = "" );

      /// Get the currently configured prefix value
      const char* GetPrefix() const;
      /// Set the prefix for the variables
      void SetPrefix( const char* prefix );

      /// Connect the object to an input TTree
      void ReadFrom( ::TTree* tree );
      /// Connect the object to an output TTree
      void WriteTo( ::TTree* tree );

      /// Turn (selected) branches either on or off
      void SetActive( ::Bool_t active = kTRUE,
                      const ::TString& pattern = ".*" );
      /// Read in all the variables that we need to write out as well
      void ReadAllActive();

      /// Clear the container. Useful when writing new branches.
      void Clear( Option_t* option = "" );
      /// Add one element to an output collection
      TriggerVecD3PDObject& Add( const TriggerVecD3PDObjectElement& el );

      /// Access a proxy class describing one element of the container
      TriggerVecD3PDObjectElement& operator[]( size_t index );
      /// Access a proxy class describing one element of the container (constant version)
      const TriggerVecD3PDObjectElement& operator[]( size_t index ) const;
      /// Add one element to an output collection
      TriggerVecD3PDObject& operator+=( const TriggerVecD3PDObjectElement& el );

      /// Did this object pass the chain EF_2e12Tvh_loose1
      VarHandle< vector<int>* > trig_EF_el_EF_2e12Tvh_loose1;
      /// Did this object pass the chain EF_2e5_tight1_Jpsi
      VarHandle< vector<int>* > trig_EF_el_EF_2e5_tight1_Jpsi;
      /// Did this object pass the chain EF_2e7T_loose1_mu6
      VarHandle< vector<int>* > trig_EF_el_EF_2e7T_loose1_mu6;
      /// Did this object pass the chain EF_2e7T_medium1_mu6
      VarHandle< vector<int>* > trig_EF_el_EF_2e7T_medium1_mu6;
      /// Did this object pass the chain EF_e11_etcut
      VarHandle< vector<int>* > trig_EF_el_EF_e11_etcut;
      /// Did this object pass the chain EF_e12Tvh_loose1
      VarHandle< vector<int>* > trig_EF_el_EF_e12Tvh_loose1;
      /// Did this object pass the chain EF_e12Tvh_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e12Tvh_medium1;
      /// Did this object pass the chain EF_e12Tvh_medium1_mu6_topo_medium
      VarHandle< vector<int>* > trig_EF_el_EF_e12Tvh_medium1_mu6_topo_medium;
      /// Did this object pass the chain EF_e12Tvh_medium1_mu8
      VarHandle< vector<int>* > trig_EF_el_EF_e12Tvh_medium1_mu8;
      /// Did this object pass the chain EF_e13_etcutTrk_xs60
      VarHandle< vector<int>* > trig_EF_el_EF_e13_etcutTrk_xs60;
      /// Did this object pass the chain EF_e13_etcutTrk_xs60_dphi2j15xe20
      VarHandle< vector<int>* > trig_EF_el_EF_e13_etcutTrk_xs60_dphi2j15xe20;
      /// Did this object pass the chain EF_e14_tight1_e4_etcut_Jpsi
      VarHandle< vector<int>* > trig_EF_el_EF_e14_tight1_e4_etcut_Jpsi;
      /// Did this object pass the chain EF_e15vh_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e15vh_medium1;
      /// Did this object pass the chain EF_e18_loose1
      VarHandle< vector<int>* > trig_EF_el_EF_e18_loose1;
      /// Did this object pass the chain EF_e18_loose1_g25_medium
      VarHandle< vector<int>* > trig_EF_el_EF_e18_loose1_g25_medium;
      /// Did this object pass the chain EF_e18_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e18_medium1;
      /// Did this object pass the chain EF_e18_medium1_g25_loose
      VarHandle< vector<int>* > trig_EF_el_EF_e18_medium1_g25_loose;
      /// Did this object pass the chain EF_e18vh_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e18vh_medium1;
      /// Did this object pass the chain EF_e18vh_medium1_2e7T_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e18vh_medium1_2e7T_medium1;
      /// Did this object pass the chain EF_e20_etcutTrk_xe30_dphi2j15xe20
      VarHandle< vector<int>* > trig_EF_el_EF_e20_etcutTrk_xe30_dphi2j15xe20;
      /// Did this object pass the chain EF_e20_etcutTrk_xs60_dphi2j15xe20
      VarHandle< vector<int>* > trig_EF_el_EF_e20_etcutTrk_xs60_dphi2j15xe20;
      /// Did this object pass the chain EF_e20vhT_medium1_g6T_etcut_Upsi
      VarHandle< vector<int>* > trig_EF_el_EF_e20vhT_medium1_g6T_etcut_Upsi;
      /// Did this object pass the chain EF_e20vhT_tight1_g6T_etcut_Upsi
      VarHandle< vector<int>* > trig_EF_el_EF_e20vhT_tight1_g6T_etcut_Upsi;
      /// Did this object pass the chain EF_e22vh_loose
      VarHandle< vector<int>* > trig_EF_el_EF_e22vh_loose;
      /// Did this object pass the chain EF_e22vh_loose0
      VarHandle< vector<int>* > trig_EF_el_EF_e22vh_loose0;
      /// Did this object pass the chain EF_e22vh_loose1
      VarHandle< vector<int>* > trig_EF_el_EF_e22vh_loose1;
      /// Did this object pass the chain EF_e22vh_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e22vh_medium1;
      /// Did this object pass the chain EF_e22vh_medium1_IDTrkNoCut
      VarHandle< vector<int>* > trig_EF_el_EF_e22vh_medium1_IDTrkNoCut;
      /// Did this object pass the chain EF_e22vhi_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e22vhi_medium1;
      /// Did this object pass the chain EF_e24vh_loose
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_loose;
      /// Did this object pass the chain EF_e24vh_loose0
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_loose0;
      /// Did this object pass the chain EF_e24vh_loose1
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_loose1;
      /// Did this object pass the chain EF_e24vh_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe30
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_EFxe30;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe30_tcem
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_EFxe30_tcem;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe35_tcem
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_EFxe35_tcem;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe35_tclcw
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_EFxe35_tclcw;
      /// Did this object pass the chain EF_e24vh_medium1_EFxe40
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_EFxe40;
      /// Did this object pass the chain EF_e24vh_medium1_IDTrkNoCut
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_IDTrkNoCut;
      /// Did this object pass the chain EF_e24vh_medium1_IdScan
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_IdScan;
      /// Did this object pass the chain EF_e24vh_medium1_L2StarB
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_L2StarB;
      /// Did this object pass the chain EF_e24vh_medium1_L2StarC
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_L2StarC;
      /// Did this object pass the chain EF_e24vh_medium1_SiTrk
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_SiTrk;
      /// Did this object pass the chain EF_e24vh_medium1_TRT
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_TRT;
      /// Did this object pass the chain EF_e24vh_medium1_b35_mediumEF_j35_a4tchad
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_b35_mediumEF_j35_a4tchad;
      /// Did this object pass the chain EF_e24vh_medium1_e7_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_medium1_e7_medium1;
      /// Did this object pass the chain EF_e24vh_tight1_e15_NoCut_Zee
      VarHandle< vector<int>* > trig_EF_el_EF_e24vh_tight1_e15_NoCut_Zee;
      /// Did this object pass the chain EF_e24vhi_loose1_mu8
      VarHandle< vector<int>* > trig_EF_el_EF_e24vhi_loose1_mu8;
      /// Did this object pass the chain EF_e24vhi_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e24vhi_medium1;
      /// Did this object pass the chain EF_e45_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e45_medium1;
      /// Did this object pass the chain EF_e5_tight1
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1;
      /// Did this object pass the chain EF_e5_tight1_e14_etcut_Jpsi
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e14_etcut_Jpsi;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_L2StarB
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_L2StarB;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_L2StarC
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_L2StarC;
      /// Did this object pass the chain EF_e5_tight1_e5_NoCut
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e5_NoCut;
      /// Did this object pass the chain EF_e5_tight1_e9_etcut_Jpsi
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e9_etcut_Jpsi;
      /// Did this object pass the chain EF_e60_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e60_medium1;
      /// Did this object pass the chain EF_e7T_loose1
      VarHandle< vector<int>* > trig_EF_el_EF_e7T_loose1;
      /// Did this object pass the chain EF_e7T_loose1_2mu6
      VarHandle< vector<int>* > trig_EF_el_EF_e7T_loose1_2mu6;
      /// Did this object pass the chain EF_e7T_medium1
      VarHandle< vector<int>* > trig_EF_el_EF_e7T_medium1;
      /// Did this object pass the chain EF_e7T_medium1_2mu6
      VarHandle< vector<int>* > trig_EF_el_EF_e7T_medium1_2mu6;
      /// Did this object pass the chain EF_e9_tight1_e4_etcut_Jpsi
      VarHandle< vector<int>* > trig_EF_el_EF_e9_tight1_e4_etcut_Jpsi;
      /// Did this object pass the chain EF_eb_physics
      VarHandle< vector<int>* > trig_EF_el_EF_eb_physics;
      /// Did this object pass the chain EF_eb_physics_empty
      VarHandle< vector<int>* > trig_EF_el_EF_eb_physics_empty;
      /// Did this object pass the chain EF_eb_physics_firstempty
      VarHandle< vector<int>* > trig_EF_el_EF_eb_physics_firstempty;
      /// Did this object pass the chain EF_eb_physics_noL1PS
      VarHandle< vector<int>* > trig_EF_el_EF_eb_physics_noL1PS;
      /// Did this object pass the chain EF_eb_physics_unpaired_iso
      VarHandle< vector<int>* > trig_EF_el_EF_eb_physics_unpaired_iso;
      /// Did this object pass the chain EF_eb_physics_unpaired_noniso
      VarHandle< vector<int>* > trig_EF_el_EF_eb_physics_unpaired_noniso;
      /// Did this object pass the chain EF_eb_random
      VarHandle< vector<int>* > trig_EF_el_EF_eb_random;
      /// Did this object pass the chain EF_eb_random_empty
      VarHandle< vector<int>* > trig_EF_el_EF_eb_random_empty;
      /// Did this object pass the chain EF_eb_random_firstempty
      VarHandle< vector<int>* > trig_EF_el_EF_eb_random_firstempty;
      /// Did this object pass the chain EF_eb_random_unpaired_iso
      VarHandle< vector<int>* > trig_EF_el_EF_eb_random_unpaired_iso;
      VarHandle< vector<float>* > trig_EF_emcl_pt;
      VarHandle< vector<float>* > trig_EF_emcl_eta;
      VarHandle< vector<float>* > trig_EF_emcl_phi;
      VarHandle< vector<float>* > trig_EF_emcl_E_em;
      VarHandle< vector<float>* > trig_EF_emcl_E_had;
      VarHandle< vector<float>* > trig_EF_emcl_slw_pt;
      VarHandle< vector<float>* > trig_EF_emcl_slw_eta;
      VarHandle< vector<float>* > trig_EF_emcl_slw_phi;
      VarHandle< vector<float>* > trig_EF_emcl_slw_E_em;
      VarHandle< vector<float>* > trig_EF_emcl_slw_E_had;
      VarHandle< vector<float>* > trig_EF_el_E;
      VarHandle< vector<float>* > trig_EF_el_Et;
      VarHandle< vector<float>* > trig_EF_el_pt;
      VarHandle< vector<float>* > trig_EF_el_m;
      VarHandle< vector<float>* > trig_EF_el_eta;
      VarHandle< vector<float>* > trig_EF_el_phi;
      VarHandle< vector<float>* > trig_EF_el_px;
      VarHandle< vector<float>* > trig_EF_el_py;
      VarHandle< vector<float>* > trig_EF_el_pz;
      VarHandle< vector<float>* > trig_EF_el_charge;
      VarHandle< vector<int>* > trig_EF_el_author;
      /// IsEM mask --- bits are set for each cut that FAILS.
      VarHandle< vector<unsigned int>* > trig_EF_el_isEM;
      /// Loose IsEM mask --- bits are set for each cut that FAILS.
      VarHandle< vector<unsigned int>* > trig_EF_el_isEMLoose;
      /// Medium IsEM mask --- bits are set for each cut that FAILS.
      VarHandle< vector<unsigned int>* > trig_EF_el_isEMMedium;
      /// Tight IsEM mask --- bits are set for each cut that FAILS.
      VarHandle< vector<unsigned int>* > trig_EF_el_isEMTight;
      VarHandle< vector<int>* > trig_EF_el_loose;
      VarHandle< vector<int>* > trig_EF_el_looseIso;
      VarHandle< vector<int>* > trig_EF_el_medium;
      VarHandle< vector<int>* > trig_EF_el_mediumIso;
      VarHandle< vector<int>* > trig_EF_el_mediumWithoutTrack;
      VarHandle< vector<int>* > trig_EF_el_mediumIsoWithoutTrack;
      VarHandle< vector<int>* > trig_EF_el_tight;
      VarHandle< vector<int>* > trig_EF_el_tightIso;
      VarHandle< vector<int>* > trig_EF_el_tightWithoutTrack;
      VarHandle< vector<int>* > trig_EF_el_tightIsoWithoutTrack;
      VarHandle< vector<int>* > trig_EF_el_loosePP;
      VarHandle< vector<int>* > trig_EF_el_loosePPIso;
      VarHandle< vector<int>* > trig_EF_el_mediumPP;
      VarHandle< vector<int>* > trig_EF_el_mediumPPIso;
      VarHandle< vector<int>* > trig_EF_el_tightPP;
      VarHandle< vector<int>* > trig_EF_el_tightPPIso;
      VarHandle< vector<float>* > trig_EF_el_vertweight;
      VarHandle< vector<int>* > trig_EF_el_hastrack;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_CB_pt;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_CB_eta;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_CB_phi;
      VarHandle< vector<vector<int> >* > trig_EF_trigmuonef_track_CB_hasCB;

      // =============================================================================
      // = Data only
      // =============================================================================
      /// Did this object pass the chain EF_2mu10
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu10;
      /// Did this object pass the chain EF_2mu10_MSonly_g10_loose
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu10_MSonly_g10_loose;
      /// Did this object pass the chain EF_2mu13
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu13;
      /// Did this object pass the chain EF_2mu13_Zmumu_IDTrkNoCut
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu13_Zmumu_IDTrkNoCut;
      /// Did this object pass the chain EF_2mu13_l2muonSA
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu13_l2muonSA;
      /// Did this object pass the chain EF_2mu15
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu15;
      /// Did this object pass the chain EF_2mu4T
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T;
      /// Did this object pass the chain EF_2mu4T_2e5_tight1
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_2e5_tight1;
      /// Did this object pass the chain EF_2mu4T_Bmumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Bmumu;
      /// Did this object pass the chain EF_2mu4T_Bmumu_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Bmumu_Barrel;
      /// Did this object pass the chain EF_2mu4T_Bmumu_BarrelOnly
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Bmumu_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_Bmumux
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Bmumux;
      /// Did this object pass the chain EF_2mu4T_Bmumux_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Bmumux_Barrel;
      /// Did this object pass the chain EF_2mu4T_Bmumux_BarrelOnly
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Bmumux_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_DiMu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_DiMu;
      /// Did this object pass the chain EF_2mu4T_DiMu_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_DiMu_Barrel;
      /// Did this object pass the chain EF_2mu4T_DiMu_BarrelOnly
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_DiMu_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_DiMu_L2StarB
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_DiMu_L2StarB;
      /// Did this object pass the chain EF_2mu4T_DiMu_L2StarC
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_DiMu_L2StarC;
      /// Did this object pass the chain EF_2mu4T_DiMu_e5_tight1
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_DiMu_e5_tight1;
      /// Did this object pass the chain EF_2mu4T_DiMu_l2muonSA
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_DiMu_l2muonSA;
      /// Did this object pass the chain EF_2mu4T_DiMu_noVtx_noOS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_DiMu_noVtx_noOS;
      /// Did this object pass the chain EF_2mu4T_Jpsimumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Jpsimumu;
      /// Did this object pass the chain EF_2mu4T_Jpsimumu_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Jpsimumu_Barrel;
      /// Did this object pass the chain EF_2mu4T_Jpsimumu_BarrelOnly
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Jpsimumu_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_Jpsimumu_IDTrkNoCut
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Jpsimumu_IDTrkNoCut;
      /// Did this object pass the chain EF_2mu4T_Upsimumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Upsimumu;
      /// Did this object pass the chain EF_2mu4T_Upsimumu_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Upsimumu_Barrel;
      /// Did this object pass the chain EF_2mu4T_Upsimumu_BarrelOnly
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_Upsimumu_BarrelOnly;
      /// Did this object pass the chain EF_2mu4T_xe60
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_xe60;
      /// Did this object pass the chain EF_2mu4T_xe60_tclcw
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu4T_xe60_tclcw;
      /// Did this object pass the chain EF_2mu6
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6;
      /// Did this object pass the chain EF_2mu6_Bmumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6_Bmumu;
      /// Did this object pass the chain EF_2mu6_Bmumux
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6_Bmumux;
      /// Did this object pass the chain EF_2mu6_DiMu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6_DiMu;
      /// Did this object pass the chain EF_2mu6_DiMu_DY20
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6_DiMu_DY20;
      /// Did this object pass the chain EF_2mu6_DiMu_DY25
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6_DiMu_DY25;
      /// Did this object pass the chain EF_2mu6_DiMu_noVtx_noOS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6_DiMu_noVtx_noOS;
      /// Did this object pass the chain EF_2mu6_Jpsimumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6_Jpsimumu;
      /// Did this object pass the chain EF_2mu6_Upsimumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6_Upsimumu;
      /// Did this object pass the chain EF_2mu6i_DiMu_DY
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6i_DiMu_DY;
      /// Did this object pass the chain EF_2mu6i_DiMu_DY_2j25_a4tchad
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6i_DiMu_DY_2j25_a4tchad;
      /// Did this object pass the chain EF_2mu6i_DiMu_DY_noVtx_noOS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6i_DiMu_DY_noVtx_noOS;
      /// Did this object pass the chain EF_2mu6i_DiMu_DY_noVtx_noOS_2j25_a4tchad
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu6i_DiMu_DY_noVtx_noOS_2j25_a4tchad;
      /// Did this object pass the chain EF_2mu8_EFxe30
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu8_EFxe30;
      /// Did this object pass the chain EF_2mu8_EFxe30_tclcw
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_2mu8_EFxe30_tclcw;
      /// Did this object pass the chain EF_mu10
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu10;
      /// Did this object pass the chain EF_mu10_Jpsimumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu10_Jpsimumu;
      /// Did this object pass the chain EF_mu10_MSonly
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu10_MSonly;
      /// Did this object pass the chain EF_mu10_Upsimumu_tight_FS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu10_Upsimumu_tight_FS;
      /// Did this object pass the chain EF_mu10i_g10_medium
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu10i_g10_medium;
      /// Did this object pass the chain EF_mu10i_g10_medium_TauMass
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu10i_g10_medium_TauMass;
      /// Did this object pass the chain EF_mu10i_loose_g12Tvh_medium
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu10i_loose_g12Tvh_medium;
      /// Did this object pass the chain EF_mu10i_loose_g12Tvh_medium_TauMass
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu10i_loose_g12Tvh_medium_TauMass;
      /// Did this object pass the chain EF_mu11_empty_NoAlg
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu11_empty_NoAlg;
      /// Did this object pass the chain EF_mu13
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu13;
      /// Did this object pass the chain EF_mu15
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu15;
      /// Did this object pass the chain EF_mu18
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18;
      /// Did this object pass the chain EF_mu18_2g10_loose
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18_2g10_loose;
      /// Did this object pass the chain EF_mu18_2g10_medium
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18_2g10_medium;
      /// Did this object pass the chain EF_mu18_IDTrkNoCut_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18_IDTrkNoCut_tight;
      /// Did this object pass the chain EF_mu18_medium
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18_medium;
      /// Did this object pass the chain EF_mu18_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18_tight;
      /// Did this object pass the chain EF_mu18_tight_2mu4_EFFS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18_tight_2mu4_EFFS;
      /// Did this object pass the chain EF_mu18_tight_e7_medium1
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18_tight_e7_medium1;
      /// Did this object pass the chain EF_mu18_tight_mu8_EFFS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18_tight_mu8_EFFS;
      /// Did this object pass the chain EF_mu18i4_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu18i4_tight;
      /// Did this object pass the chain EF_mu20i_tight_g5_loose_TauMass
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu20i_tight_g5_loose_TauMass;
      /// Did this object pass the chain EF_mu20i_tight_g5_medium
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu20i_tight_g5_medium;
      /// Did this object pass the chain EF_mu20i_tight_g5_medium_TauMass
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu20i_tight_g5_medium_TauMass;
      /// Did this object pass the chain EF_mu20it_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu20it_tight;
      /// Did this object pass the chain EF_mu22_IDTrkNoCut_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu22_IDTrkNoCut_tight;
      /// Did this object pass the chain EF_mu24
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24;
      /// Did this object pass the chain EF_mu24_g20vh_loose
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_g20vh_loose;
      /// Did this object pass the chain EF_mu24_g20vh_medium
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_g20vh_medium;
      /// Did this object pass the chain EF_mu24_j65_a4tchad
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_j65_a4tchad;
      /// Did this object pass the chain EF_mu24_j65_a4tchad_EFxe40
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_j65_a4tchad_EFxe40;
      /// Did this object pass the chain EF_mu24_j65_a4tchad_EFxe40_tclcw
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_j65_a4tchad_EFxe40_tclcw;
      /// Did this object pass the chain EF_mu24_j65_a4tchad_EFxe60_tclcw
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_j65_a4tchad_EFxe60_tclcw;
      /// Did this object pass the chain EF_mu24_medium
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_medium;
      /// Did this object pass the chain EF_mu24_muCombTag_NoEF_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_muCombTag_NoEF_tight;
      /// Did this object pass the chain EF_mu24_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight;
      /// Did this object pass the chain EF_mu24_tight_3j35_a4tchad
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight_3j35_a4tchad;
      /// Did this object pass the chain EF_mu24_tight_EFxe40
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight_EFxe40;
      /// Did this object pass the chain EF_mu24_tight_L2StarB
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight_L2StarB;
      /// Did this object pass the chain EF_mu24_tight_L2StarC
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight_L2StarC;
      /// Did this object pass the chain EF_mu24_tight_MG
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight_MG;
      /// Did this object pass the chain EF_mu24_tight_MuonEF
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight_MuonEF;
      /// Did this object pass the chain EF_mu24_tight_b35_mediumEF_j35_a4tchad
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight_b35_mediumEF_j35_a4tchad;
      /// Did this object pass the chain EF_mu24_tight_mu6_EFFS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24_tight_mu6_EFFS;
      /// Did this object pass the chain EF_mu24i_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24i_tight;
      /// Did this object pass the chain EF_mu24i_tight_MG
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24i_tight_MG;
      /// Did this object pass the chain EF_mu24i_tight_MuonEF
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24i_tight_MuonEF;
      /// Did this object pass the chain EF_mu24i_tight_l2muonSA
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu24i_tight_l2muonSA;
      /// Did this object pass the chain EF_mu36_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu36_tight;
      /// Did this object pass the chain EF_mu40_MSonly_barrel_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu40_MSonly_barrel_tight;
      /// Did this object pass the chain EF_mu40_muCombTag_NoEF
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu40_muCombTag_NoEF;
      /// Did this object pass the chain EF_mu40_slow_outOfTime_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu40_slow_outOfTime_tight;
      /// Did this object pass the chain EF_mu40_slow_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu40_slow_tight;
      /// Did this object pass the chain EF_mu40_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu40_tight;
      /// Did this object pass the chain EF_mu4T
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T;
      /// Did this object pass the chain EF_mu4T_cosmic
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_cosmic;
      /// Did this object pass the chain EF_mu4T_j110_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j110_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j110_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j110_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j145_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j145_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j145_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j145_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j15_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j15_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j15_a4tchad_matchedZ
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j15_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j180_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j180_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j180_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j180_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j220_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j220_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j220_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j220_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j25_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j25_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j25_a4tchad_matchedZ
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j25_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j280_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j280_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j280_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j280_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j35_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j35_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j35_a4tchad_matchedZ
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j35_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j45_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j45_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j45_a4tchad_L2FS_matchedZ
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j45_a4tchad_L2FS_matchedZ;
      /// Did this object pass the chain EF_mu4T_j45_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j45_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j45_a4tchad_matchedZ
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j45_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j55_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j55_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j55_a4tchad_L2FS_matchedZ
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j55_a4tchad_L2FS_matchedZ;
      /// Did this object pass the chain EF_mu4T_j55_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j55_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j55_a4tchad_matchedZ
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j55_a4tchad_matchedZ;
      /// Did this object pass the chain EF_mu4T_j65_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j65_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j65_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j65_a4tchad_matched;
      /// Did this object pass the chain EF_mu4T_j65_a4tchad_xe60_tclcw_loose
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j65_a4tchad_xe60_tclcw_loose;
      /// Did this object pass the chain EF_mu4T_j65_a4tchad_xe70_tclcw_veryloose
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j65_a4tchad_xe70_tclcw_veryloose;
      /// Did this object pass the chain EF_mu4T_j80_a4tchad_L2FS_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j80_a4tchad_L2FS_matched;
      /// Did this object pass the chain EF_mu4T_j80_a4tchad_matched
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4T_j80_a4tchad_matched;
      /// Did this object pass the chain EF_mu4Ti_g20Tvh_medium
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Ti_g20Tvh_medium;
      /// Did this object pass the chain EF_mu4Ti_g20Tvh_medium_TauMass
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Ti_g20Tvh_medium_TauMass;
      /// Did this object pass the chain EF_mu4Tmu6_Bmumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Bmumu;
      /// Did this object pass the chain EF_mu4Tmu6_Bmumu_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Bmumu_Barrel;
      /// Did this object pass the chain EF_mu4Tmu6_Bmumux
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Bmumux;
      /// Did this object pass the chain EF_mu4Tmu6_Bmumux_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Bmumux_Barrel;
      /// Did this object pass the chain EF_mu4Tmu6_DiMu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_DiMu;
      /// Did this object pass the chain EF_mu4Tmu6_DiMu_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_DiMu_Barrel;
      /// Did this object pass the chain EF_mu4Tmu6_DiMu_noVtx_noOS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_DiMu_noVtx_noOS;
      /// Did this object pass the chain EF_mu4Tmu6_Jpsimumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Jpsimumu;
      /// Did this object pass the chain EF_mu4Tmu6_Jpsimumu_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Jpsimumu_Barrel;
      /// Did this object pass the chain EF_mu4Tmu6_Jpsimumu_IDTrkNoCut
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Jpsimumu_IDTrkNoCut;
      /// Did this object pass the chain EF_mu4Tmu6_Upsimumu
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Upsimumu;
      /// Did this object pass the chain EF_mu4Tmu6_Upsimumu_Barrel
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4Tmu6_Upsimumu_Barrel;
      /// Did this object pass the chain EF_mu4_L1MU11_MSonly_cosmic
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4_L1MU11_MSonly_cosmic;
      /// Did this object pass the chain EF_mu4_L1MU11_cosmic
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4_L1MU11_cosmic;
      /// Did this object pass the chain EF_mu4_empty_NoAlg
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4_empty_NoAlg;
      /// Did this object pass the chain EF_mu4_firstempty_NoAlg
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4_firstempty_NoAlg;
      /// Did this object pass the chain EF_mu4_unpaired_iso_NoAlg
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu4_unpaired_iso_NoAlg;
      /// Did this object pass the chain EF_mu50_MSonly_barrel_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu50_MSonly_barrel_tight;
      /// Did this object pass the chain EF_mu6
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu6;
      /// Did this object pass the chain EF_mu60_slow_outOfTime_tight1
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu60_slow_outOfTime_tight1;
      /// Did this object pass the chain EF_mu60_slow_tight1
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu60_slow_tight1;
      /// Did this object pass the chain EF_mu6_Jpsimumu_tight
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu6_Jpsimumu_tight;
      /// Did this object pass the chain EF_mu6_MSonly
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu6_MSonly;
      /// Did this object pass the chain EF_mu6_Trk_Jpsi_loose
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu6_Trk_Jpsi_loose;
      /// Did this object pass the chain EF_mu8
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu8;
      /// Did this object pass the chain EF_mu8_4j45_a4tchad_L2FS
      VarHandle< vector<int>* > trig_EF_trigmuonef_EF_mu8_4j45_a4tchad_L2FS;
      VarHandle< vector<vector<int> >* > trig_EF_trigmuonef_track_MuonType;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_MS_pt;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_MS_eta;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_MS_phi;
      VarHandle< vector<vector<int> >* > trig_EF_trigmuonef_track_MS_hasMS;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_SA_pt;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_SA_eta;
      VarHandle< vector<vector<float> >* > trig_EF_trigmuonef_track_SA_phi;
      VarHandle< vector<vector<int> >* > trig_EF_trigmuonef_track_SA_hasSA;
      
      // =============================================================================
      // = MC only
      // =============================================================================
      /// Did this object pass the chain EF_e12Tvh_loose1_mu8
      VarHandle< vector<int>* > trig_EF_el_EF_e12Tvh_loose1_mu8;
      /// Did this object pass the chain EF_e12Tvh_medium1_mu10
      VarHandle< vector<int>* > trig_EF_el_EF_e12Tvh_medium1_mu10;
      /// Did this object pass the chain EF_e12Tvh_medium1_mu6
      VarHandle< vector<int>* > trig_EF_el_EF_e12Tvh_medium1_mu6;
      /// Did this object pass the chain EF_e18_loose1_g35_loose
      VarHandle< vector<int>* > trig_EF_el_EF_e18_loose1_g35_loose;
      /// Did this object pass the chain EF_e18_loose1_g35_medium
      VarHandle< vector<int>* > trig_EF_el_EF_e18_loose1_g35_medium;
      /// Did this object pass the chain EF_e18_medium1_g25_medium
      VarHandle< vector<int>* > trig_EF_el_EF_e18_medium1_g25_medium;
      /// Did this object pass the chain EF_e18_medium1_g35_loose
      VarHandle< vector<int>* > trig_EF_el_EF_e18_medium1_g35_loose;
      /// Did this object pass the chain EF_e18_medium1_g35_medium
      VarHandle< vector<int>* > trig_EF_el_EF_e18_medium1_g35_medium;
      /// Did this object pass the chain EF_e22vh_medium1_IdScan
      VarHandle< vector<int>* > trig_EF_el_EF_e22vh_medium1_IdScan;
      /// Did this object pass the chain EF_e22vh_medium1_SiTrk
      VarHandle< vector<int>* > trig_EF_el_EF_e22vh_medium1_SiTrk;
      /// Did this object pass the chain EF_e22vh_medium1_TRT
      VarHandle< vector<int>* > trig_EF_el_EF_e22vh_medium1_TRT;
      /// Did this object pass the chain EF_e45_etcut
      VarHandle< vector<int>* > trig_EF_el_EF_e45_etcut;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_IdScan
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_IdScan;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_SiTrk
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_SiTrk;
      /// Did this object pass the chain EF_e5_tight1_e4_etcut_Jpsi_TRT
      VarHandle< vector<int>* > trig_EF_el_EF_e5_tight1_e4_etcut_Jpsi_TRT;
      /// Did this object pass the chain EF_e60_etcut
      VarHandle< vector<int>* > trig_EF_el_EF_e60_etcut;
      

   private:
      mutable std::vector< TriggerVecD3PDObjectElement > fProxies; ///< Internal list of proxy objects
      std::map< ::TString, VarHandleBase* > fHandles; ///< Book-keeper of the VarHandle members
      const ::Bool_t fFromInput; ///< Flag specifying if object is used for D3PD reading
      const ::TString fPrefix; ///< Prefix to the branch names

      ClassDef( TriggerVecD3PDObject, 0 )

   }; // class TriggerVecD3PDObject

} // namespace D3PDReader

#endif // D3PDREADER_TriggerVecD3PDObject_H
