// Dear emacs, this is -*- c++ -*-
// -------------------------------------------------------------
//             Code produced by D3PDMakerReader
//
//  author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
// -------------------------------------------------------------
#ifndef D3PDREADER_TriggerD3PDObject_H
#define D3PDREADER_TriggerD3PDObject_H

#include <map>

#include <TObject.h>
#include <TString.h>

#include "VarHandle.h"

class TTree;

namespace D3PDReader {

   /**
    * Code generated by CodeGenerator_v2 on:
    *  host = pc-penn-d-07
    *  OS   = Linux / 2.6.18-274.18.1.el5
    *  user = bjackson
    */
   class TriggerD3PDObject : public TObject {

   public:
      /// Constructor used when reading from a TTree
      TriggerD3PDObject( const ::Long64_t& master, const char* prefix = "" );
      /// Constructor when the object is only used for writing data out
      TriggerD3PDObject( const char* prefix = "" );

      /// Get the currently configured prefix value
      const char* GetPrefix() const;
      /// Set the prefix for the variables
      void SetPrefix( const char* prefix );

      /// Connect the object to an input TTree
      void ReadFrom( ::TTree* tree );
      /// Connect the object to an output TTree
      void WriteTo( ::TTree* tree );

      /// Turn (selected) branches either on or off
      void SetActive( ::Bool_t active = kTRUE,
                      const ::TString& pattern = ".*" );
      /// Read in all the variables that we need to write out as well
      void ReadAllActive();

      /// Did this event pass trigger EF_2e12Tvh_loose1
      VarHandle< Bool_t > EF_2e12Tvh_loose1;
// -- slimmed --       /// Did this event pass trigger EF_2e5_tight1_Jpsi
// -- slimmed --       VarHandle< Bool_t > EF_2e5_tight1_Jpsi;
      /// Did this event pass trigger EF_2e7T_loose1_mu6
      VarHandle< Bool_t > EF_2e7T_loose1_mu6;
      /// Did this event pass trigger EF_2e7T_medium1_mu6
      VarHandle< Bool_t > EF_2e7T_medium1_mu6;
// -- slimmed --       /// Did this event pass trigger EF_2g15vh_medium_g10_medium
// -- slimmed --       VarHandle< Bool_t > EF_2g15vh_medium_g10_medium;
// -- slimmed --       /// Did this event pass trigger EF_2g20vh_medium
// -- slimmed --       VarHandle< Bool_t > EF_2g20vh_medium;
// -- slimmed --       /// Did this event pass trigger EF_2g40_loose
// -- slimmed --       VarHandle< Bool_t > EF_2g40_loose;
      /// Did this event pass trigger EF_2mu10
      VarHandle< Bool_t > EF_2mu10;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu10_MSonly_g10_loose
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu10_MSonly_g10_loose;
      /// Did this event pass trigger EF_2mu13
      VarHandle< Bool_t > EF_2mu13;
// -- slimmed --       /// Did this event pass trigger EF_2mu13_Zmumu_IDTrkNoCut
// -- slimmed --       VarHandle< Bool_t > EF_2mu13_Zmumu_IDTrkNoCut;
// -- slimmed --       /// Did this event pass trigger EF_2mu13_l2muonSA
// -- slimmed --       VarHandle< Bool_t > EF_2mu13_l2muonSA;
      /// Did this event pass trigger EF_2mu15
      VarHandle< Bool_t > EF_2mu15;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_2e5_tight1
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_2e5_tight1;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_Bmumu
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Bmumu;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_Bmumu_Barrel
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Bmumu_Barrel;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_Bmumu_BarrelOnly
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Bmumu_BarrelOnly;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_Bmumux
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Bmumux;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_Bmumux_Barrel
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Bmumux_Barrel;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_Bmumux_BarrelOnly
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Bmumux_BarrelOnly;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_DiMu
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_DiMu;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_DiMu_Barrel
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_DiMu_Barrel;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_DiMu_BarrelOnly
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_DiMu_BarrelOnly;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_DiMu_L2StarB
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_DiMu_L2StarB;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_DiMu_L2StarC
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_DiMu_L2StarC;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_DiMu_e5_tight1
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_DiMu_e5_tight1;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_DiMu_l2muonSA
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_DiMu_l2muonSA;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_DiMu_noVtx_noOS
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_DiMu_noVtx_noOS;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_Jpsimumu
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Jpsimumu;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_Jpsimumu_Barrel
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Jpsimumu_Barrel;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_Jpsimumu_BarrelOnly
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Jpsimumu_BarrelOnly;
// -- slimmed -- // -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_Jpsimumu_IDTrkNoCut
// -- slimmed -- // -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Jpsimumu_IDTrkNoCut;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_Upsimumu
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Upsimumu;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_Upsimumu_Barrel
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Upsimumu_Barrel;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu4T_Upsimumu_BarrelOnly
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu4T_Upsimumu_BarrelOnly;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_xe60
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_xe60;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_xe60_tclcw
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_xe60_tclcw;
      /// Did this event pass trigger EF_2mu6
      VarHandle< Bool_t > EF_2mu6;
      /// Did this event pass trigger EF_2mu6_Bmumu
      VarHandle< Bool_t > EF_2mu6_Bmumu;
      /// Did this event pass trigger EF_2mu6_Bmumux
      VarHandle< Bool_t > EF_2mu6_Bmumux;
      /// Did this event pass trigger EF_2mu6_DiMu
      VarHandle< Bool_t > EF_2mu6_DiMu;
      /// Did this event pass trigger EF_2mu6_DiMu_DY20
      VarHandle< Bool_t > EF_2mu6_DiMu_DY20;
      /// Did this event pass trigger EF_2mu6_DiMu_DY25
      VarHandle< Bool_t > EF_2mu6_DiMu_DY25;
      /// Did this event pass trigger EF_2mu6_DiMu_noVtx_noOS
      VarHandle< Bool_t > EF_2mu6_DiMu_noVtx_noOS;
// -- slimmed --       /// Did this event pass trigger EF_2mu6_Jpsimumu
// -- slimmed --       VarHandle< Bool_t > EF_2mu6_Jpsimumu;
// -- slimmed --       /// Did this event pass trigger EF_2mu6_Upsimumu
// -- slimmed --       VarHandle< Bool_t > EF_2mu6_Upsimumu;
      /// Did this event pass trigger EF_2mu6i_DiMu_DY
      VarHandle< Bool_t > EF_2mu6i_DiMu_DY;
      /// Did this event pass trigger EF_2mu6i_DiMu_DY_2j25_a4tchad
      VarHandle< Bool_t > EF_2mu6i_DiMu_DY_2j25_a4tchad;
      /// Did this event pass trigger EF_2mu6i_DiMu_DY_noVtx_noOS
      VarHandle< Bool_t > EF_2mu6i_DiMu_DY_noVtx_noOS;
      /// Did this event pass trigger EF_2mu6i_DiMu_DY_noVtx_noOS_2j25_a4tchad
      VarHandle< Bool_t > EF_2mu6i_DiMu_DY_noVtx_noOS_2j25_a4tchad;
      /// Did this event pass trigger EF_2mu8_EFxe30
      VarHandle< Bool_t > EF_2mu8_EFxe30;
      /// Did this event pass trigger EF_2mu8_EFxe30_tclcw
      VarHandle< Bool_t > EF_2mu8_EFxe30_tclcw;
      /// Did this event pass trigger EF_e11_etcut
      VarHandle< Bool_t > EF_e11_etcut;
      /// Did this event pass trigger EF_e12Tvh_loose1
      VarHandle< Bool_t > EF_e12Tvh_loose1;
      /// Did this event pass trigger EF_e12Tvh_medium1
      VarHandle< Bool_t > EF_e12Tvh_medium1;
      /// Did this event pass trigger EF_e12Tvh_medium1_mu6_topo_medium
      VarHandle< Bool_t > EF_e12Tvh_medium1_mu6_topo_medium;
      /// Did this event pass trigger EF_e12Tvh_medium1_mu8
      VarHandle< Bool_t > EF_e12Tvh_medium1_mu8;
// -- slimmed --       /// Did this event pass trigger EF_e13_etcutTrk_xs60
// -- slimmed --       VarHandle< Bool_t > EF_e13_etcutTrk_xs60;
// -- slimmed --       /// Did this event pass trigger EF_e13_etcutTrk_xs60_dphi2j15xe20
// -- slimmed --       VarHandle< Bool_t > EF_e13_etcutTrk_xs60_dphi2j15xe20;
// -- slimmed --       /// Did this event pass trigger EF_e14_tight1_e4_etcut_Jpsi
// -- slimmed --       VarHandle< Bool_t > EF_e14_tight1_e4_etcut_Jpsi;
      /// Did this event pass trigger EF_e15vh_medium1
      VarHandle< Bool_t > EF_e15vh_medium1;
      /// Did this event pass trigger EF_e18_loose1
      VarHandle< Bool_t > EF_e18_loose1;
// -- slimmed --       /// Did this event pass trigger EF_e18_loose1_g25_medium
// -- slimmed --       VarHandle< Bool_t > EF_e18_loose1_g25_medium;
      /// Did this event pass trigger EF_e18_medium1
      VarHandle< Bool_t > EF_e18_medium1;
// -- slimmed --       /// Did this event pass trigger EF_e18_medium1_g25_loose
// -- slimmed --       VarHandle< Bool_t > EF_e18_medium1_g25_loose;
      /// Did this event pass trigger EF_e18vh_medium1
      VarHandle< Bool_t > EF_e18vh_medium1;
      /// Did this event pass trigger EF_e18vh_medium1_2e7T_medium1
      VarHandle< Bool_t > EF_e18vh_medium1_2e7T_medium1;
      /// Did this event pass trigger EF_e20_etcutTrk_xe30_dphi2j15xe20
      VarHandle< Bool_t > EF_e20_etcutTrk_xe30_dphi2j15xe20;
// -- slimmed --       /// Did this event pass trigger EF_e20_etcutTrk_xs60_dphi2j15xe20
// -- slimmed --       VarHandle< Bool_t > EF_e20_etcutTrk_xs60_dphi2j15xe20;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_e20vhT_medium1_g6T_etcut_Upsi
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_e20vhT_medium1_g6T_etcut_Upsi;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_e20vhT_tight1_g6T_etcut_Upsi
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_e20vhT_tight1_g6T_etcut_Upsi;
      /// Did this event pass trigger EF_e22vh_loose
      VarHandle< Bool_t > EF_e22vh_loose;
      /// Did this event pass trigger EF_e22vh_loose0
      VarHandle< Bool_t > EF_e22vh_loose0;
      /// Did this event pass trigger EF_e22vh_loose1
      VarHandle< Bool_t > EF_e22vh_loose1;
      /// Did this event pass trigger EF_e22vh_medium1
      VarHandle< Bool_t > EF_e22vh_medium1;
// -- slimmed --       /// Did this event pass trigger EF_e22vh_medium1_IDTrkNoCut
// -- slimmed --       VarHandle< Bool_t > EF_e22vh_medium1_IDTrkNoCut;
      /// Did this event pass trigger EF_e22vhi_medium1
      VarHandle< Bool_t > EF_e22vhi_medium1;
      /// Did this event pass trigger EF_e24vh_loose
      VarHandle< Bool_t > EF_e24vh_loose;
      /// Did this event pass trigger EF_e24vh_loose0
      VarHandle< Bool_t > EF_e24vh_loose0;
      /// Did this event pass trigger EF_e24vh_loose1
      VarHandle< Bool_t > EF_e24vh_loose1;
      /// Did this event pass trigger EF_e24vh_medium1
      VarHandle< Bool_t > EF_e24vh_medium1;
      /// Did this event pass trigger EF_e24vh_medium1_EFxe30
      VarHandle< Bool_t > EF_e24vh_medium1_EFxe30;
      /// Did this event pass trigger EF_e24vh_medium1_EFxe30_tcem
      VarHandle< Bool_t > EF_e24vh_medium1_EFxe30_tcem;
      /// Did this event pass trigger EF_e24vh_medium1_EFxe35_tcem
      VarHandle< Bool_t > EF_e24vh_medium1_EFxe35_tcem;
      /// Did this event pass trigger EF_e24vh_medium1_EFxe35_tclcw
      VarHandle< Bool_t > EF_e24vh_medium1_EFxe35_tclcw;
      /// Did this event pass trigger EF_e24vh_medium1_EFxe40
      VarHandle< Bool_t > EF_e24vh_medium1_EFxe40;
// -- slimmed --       /// Did this event pass trigger EF_e24vh_medium1_IDTrkNoCut
// -- slimmed --       VarHandle< Bool_t > EF_e24vh_medium1_IDTrkNoCut;
      /// Did this event pass trigger EF_e24vh_medium1_IdScan
      VarHandle< Bool_t > EF_e24vh_medium1_IdScan;
// -- slimmed --       /// Did this event pass trigger EF_e24vh_medium1_L2StarB
// -- slimmed --       VarHandle< Bool_t > EF_e24vh_medium1_L2StarB;
// -- slimmed --       /// Did this event pass trigger EF_e24vh_medium1_L2StarC
// -- slimmed --       VarHandle< Bool_t > EF_e24vh_medium1_L2StarC;
      /// Did this event pass trigger EF_e24vh_medium1_SiTrk
      VarHandle< Bool_t > EF_e24vh_medium1_SiTrk;
      /// Did this event pass trigger EF_e24vh_medium1_TRT
      VarHandle< Bool_t > EF_e24vh_medium1_TRT;
      /// Did this event pass trigger EF_e24vh_medium1_b35_mediumEF_j35_a4tchad
      VarHandle< Bool_t > EF_e24vh_medium1_b35_mediumEF_j35_a4tchad;
      /// Did this event pass trigger EF_e24vh_medium1_e7_medium1
      VarHandle< Bool_t > EF_e24vh_medium1_e7_medium1;
      /// Did this event pass trigger EF_e24vh_tight1_e15_NoCut_Zee
      VarHandle< Bool_t > EF_e24vh_tight1_e15_NoCut_Zee;
      /// Did this event pass trigger EF_e24vhi_loose1_mu8
      VarHandle< Bool_t > EF_e24vhi_loose1_mu8;
      /// Did this event pass trigger EF_e24vhi_medium1
      VarHandle< Bool_t > EF_e24vhi_medium1;
      /// Did this event pass trigger EF_e45_medium1
      VarHandle< Bool_t > EF_e45_medium1;
      /// Did this event pass trigger EF_e5_tight1
      VarHandle< Bool_t > EF_e5_tight1;
// -- slimmed --       /// Did this event pass trigger EF_e5_tight1_e14_etcut_Jpsi
// -- slimmed --       VarHandle< Bool_t > EF_e5_tight1_e14_etcut_Jpsi;
// -- slimmed --       /// Did this event pass trigger EF_e5_tight1_e4_etcut_Jpsi
// -- slimmed --       VarHandle< Bool_t > EF_e5_tight1_e4_etcut_Jpsi;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_e5_tight1_e4_etcut_Jpsi_L2StarB
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_e5_tight1_e4_etcut_Jpsi_L2StarB;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_e5_tight1_e4_etcut_Jpsi_L2StarC
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_e5_tight1_e4_etcut_Jpsi_L2StarC;
      /// Did this event pass trigger EF_e5_tight1_e5_NoCut
      VarHandle< Bool_t > EF_e5_tight1_e5_NoCut;
// -- slimmed --       /// Did this event pass trigger EF_e5_tight1_e9_etcut_Jpsi
// -- slimmed --       VarHandle< Bool_t > EF_e5_tight1_e9_etcut_Jpsi;
      /// Did this event pass trigger EF_e60_medium1
      VarHandle< Bool_t > EF_e60_medium1;
      /// Did this event pass trigger EF_e7T_loose1
      VarHandle< Bool_t > EF_e7T_loose1;
      /// Did this event pass trigger EF_e7T_loose1_2mu6
      VarHandle< Bool_t > EF_e7T_loose1_2mu6;
      /// Did this event pass trigger EF_e7T_medium1
      VarHandle< Bool_t > EF_e7T_medium1;
      /// Did this event pass trigger EF_e7T_medium1_2mu6
      VarHandle< Bool_t > EF_e7T_medium1_2mu6;
// -- slimmed --       /// Did this event pass trigger EF_e9_tight1_e4_etcut_Jpsi
// -- slimmed --       VarHandle< Bool_t > EF_e9_tight1_e4_etcut_Jpsi;
// -- slimmed --       /// Did this event pass trigger EF_eb_physics
// -- slimmed --       VarHandle< Bool_t > EF_eb_physics;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_eb_physics_empty
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_eb_physics_empty;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_eb_physics_firstempty
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_eb_physics_firstempty;
// -- slimmed --       /// Did this event pass trigger EF_eb_physics_noL1PS
// -- slimmed --       VarHandle< Bool_t > EF_eb_physics_noL1PS;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_eb_physics_unpaired_iso
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_eb_physics_unpaired_iso;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_eb_physics_unpaired_noniso
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_eb_physics_unpaired_noniso;
// -- slimmed --       /// Did this event pass trigger EF_eb_random
// -- slimmed --       VarHandle< Bool_t > EF_eb_random;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_eb_random_empty
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_eb_random_empty;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_eb_random_firstempty
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_eb_random_firstempty;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_eb_random_unpaired_iso
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_eb_random_unpaired_iso;
// -- slimmed --       /// Did this event pass trigger EF_g100_loose
// -- slimmed --       VarHandle< Bool_t > EF_g100_loose;
// -- slimmed --       /// Did this event pass trigger EF_g10_NoCut_cosmic
// -- slimmed --       VarHandle< Bool_t > EF_g10_NoCut_cosmic;
// -- slimmed --       /// Did this event pass trigger EF_g10_loose
// -- slimmed --       VarHandle< Bool_t > EF_g10_loose;
// -- slimmed --       /// Did this event pass trigger EF_g10_medium
// -- slimmed --       VarHandle< Bool_t > EF_g10_medium;
// -- slimmed --       /// Did this event pass trigger EF_g120_loose
// -- slimmed --       VarHandle< Bool_t > EF_g120_loose;
// -- slimmed --       /// Did this event pass trigger EF_g12Tvh_loose
// -- slimmed --       VarHandle< Bool_t > EF_g12Tvh_loose;
// -- slimmed --       /// Did this event pass trigger EF_g12Tvh_loose_larcalib
// -- slimmed --       VarHandle< Bool_t > EF_g12Tvh_loose_larcalib;
// -- slimmed --       /// Did this event pass trigger EF_g15_loose
// -- slimmed --       VarHandle< Bool_t > EF_g15_loose;
// -- slimmed --       /// Did this event pass trigger EF_g15vh_medium
// -- slimmed --       VarHandle< Bool_t > EF_g15vh_medium;
// -- slimmed --       /// Did this event pass trigger EF_g200_etcut
// -- slimmed --       VarHandle< Bool_t > EF_g200_etcut;
// -- slimmed --       /// Did this event pass trigger EF_g20_etcut
// -- slimmed --       VarHandle< Bool_t > EF_g20_etcut;
// -- slimmed --       /// Did this event pass trigger EF_g20_loose
// -- slimmed --       VarHandle< Bool_t > EF_g20_loose;
// -- slimmed --       /// Did this event pass trigger EF_g20_loose_larcalib
// -- slimmed --       VarHandle< Bool_t > EF_g20_loose_larcalib;
// -- slimmed --       /// Did this event pass trigger EF_g20_medium
// -- slimmed --       VarHandle< Bool_t > EF_g20_medium;
// -- slimmed --       /// Did this event pass trigger EF_g30_loose_g20_loose
// -- slimmed --       VarHandle< Bool_t > EF_g30_loose_g20_loose;
// -- slimmed --       /// Did this event pass trigger EF_g30_medium_g20_medium
// -- slimmed --       VarHandle< Bool_t > EF_g30_medium_g20_medium;
// -- slimmed --       /// Did this event pass trigger EF_g35_loose_g25_loose
// -- slimmed --       VarHandle< Bool_t > EF_g35_loose_g25_loose;
// -- slimmed --       /// Did this event pass trigger EF_g35_loose_g30_loose
// -- slimmed --       VarHandle< Bool_t > EF_g35_loose_g30_loose;
// -- slimmed --       /// Did this event pass trigger EF_g40_loose
// -- slimmed --       VarHandle< Bool_t > EF_g40_loose;
// -- slimmed --       /// Did this event pass trigger EF_g40_loose_L2EFxe60
// -- slimmed --       VarHandle< Bool_t > EF_g40_loose_L2EFxe60;
// -- slimmed --       /// Did this event pass trigger EF_g40_loose_L2EFxe60_tclcw
// -- slimmed --       VarHandle< Bool_t > EF_g40_loose_L2EFxe60_tclcw;
// -- slimmed --       /// Did this event pass trigger EF_g40_loose_g25_loose
// -- slimmed --       VarHandle< Bool_t > EF_g40_loose_g25_loose;
// -- slimmed --       /// Did this event pass trigger EF_g40_loose_g30_loose
// -- slimmed --       VarHandle< Bool_t > EF_g40_loose_g30_loose;
// -- slimmed --       /// Did this event pass trigger EF_g40_loose_larcalib
// -- slimmed --       VarHandle< Bool_t > EF_g40_loose_larcalib;
// -- slimmed --       /// Did this event pass trigger EF_g5_NoCut_cosmic
// -- slimmed --       VarHandle< Bool_t > EF_g5_NoCut_cosmic;
// -- slimmed --       /// Did this event pass trigger EF_g60_loose
// -- slimmed --       VarHandle< Bool_t > EF_g60_loose;
// -- slimmed --       /// Did this event pass trigger EF_g60_loose_larcalib
// -- slimmed --       VarHandle< Bool_t > EF_g60_loose_larcalib;
// -- slimmed --       /// Did this event pass trigger EF_g80_loose
// -- slimmed --       VarHandle< Bool_t > EF_g80_loose;
// -- slimmed --       /// Did this event pass trigger EF_g80_loose_larcalib
// -- slimmed --       VarHandle< Bool_t > EF_g80_loose_larcalib;
      /// Did this event pass trigger EF_mu10
      VarHandle< Bool_t > EF_mu10;
// -- slimmed --       /// Did this event pass trigger EF_mu10_Jpsimumu
// -- slimmed --       VarHandle< Bool_t > EF_mu10_Jpsimumu;
// -- slimmed --       /// Did this event pass trigger EF_mu10_MSonly
// -- slimmed --       VarHandle< Bool_t > EF_mu10_MSonly;
// -- slimmed --       /// Did this event pass trigger EF_mu10_Upsimumu_tight_FS
// -- slimmed --       VarHandle< Bool_t > EF_mu10_Upsimumu_tight_FS;
// -- slimmed --       /// Did this event pass trigger EF_mu10i_g10_medium
// -- slimmed --       VarHandle< Bool_t > EF_mu10i_g10_medium;
// -- slimmed --       /// Did this event pass trigger EF_mu10i_g10_medium_TauMass
// -- slimmed --       VarHandle< Bool_t > EF_mu10i_g10_medium_TauMass;
// -- slimmed --       /// Did this event pass trigger EF_mu10i_loose_g12Tvh_medium
// -- slimmed --       VarHandle< Bool_t > EF_mu10i_loose_g12Tvh_medium;
// -- slimmed --       /// Did this event pass trigger EF_mu10i_loose_g12Tvh_medium_TauMass
// -- slimmed --       VarHandle< Bool_t > EF_mu10i_loose_g12Tvh_medium_TauMass;
// -- slimmed --       /// Did this event pass trigger EF_mu11_empty_NoAlg
// -- slimmed --       VarHandle< Bool_t > EF_mu11_empty_NoAlg;
      /// Did this event pass trigger EF_mu13
      VarHandle< Bool_t > EF_mu13;
      /// Did this event pass trigger EF_mu15
      VarHandle< Bool_t > EF_mu15;
      /// Did this event pass trigger EF_mu18
      VarHandle< Bool_t > EF_mu18;
// -- slimmed --       /// Did this event pass trigger EF_mu18_2g10_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu18_2g10_loose;
// -- slimmed --       /// Did this event pass trigger EF_mu18_2g10_medium
// -- slimmed --       VarHandle< Bool_t > EF_mu18_2g10_medium;
// -- slimmed --       /// Did this event pass trigger EF_mu18_IDTrkNoCut_tight
// -- slimmed --       VarHandle< Bool_t > EF_mu18_IDTrkNoCut_tight;
      /// Did this event pass trigger EF_mu18_medium
      VarHandle< Bool_t > EF_mu18_medium;
      /// Did this event pass trigger EF_mu18_tight
      VarHandle< Bool_t > EF_mu18_tight;
      /// Did this event pass trigger EF_mu18_tight_2mu4_EFFS
      VarHandle< Bool_t > EF_mu18_tight_2mu4_EFFS;
      /// Did this event pass trigger EF_mu18_tight_e7_medium1
      VarHandle< Bool_t > EF_mu18_tight_e7_medium1;
      /// Did this event pass trigger EF_mu18_tight_mu8_EFFS
      VarHandle< Bool_t > EF_mu18_tight_mu8_EFFS;
      /// Did this event pass trigger EF_mu18i4_tight
      VarHandle< Bool_t > EF_mu18i4_tight;
// -- slimmed --       /// Did this event pass trigger EF_mu20i_tight_g5_loose_TauMass
// -- slimmed --       VarHandle< Bool_t > EF_mu20i_tight_g5_loose_TauMass;
// -- slimmed --       /// Did this event pass trigger EF_mu20i_tight_g5_medium
// -- slimmed --       VarHandle< Bool_t > EF_mu20i_tight_g5_medium;
// -- slimmed --       /// Did this event pass trigger EF_mu20i_tight_g5_medium_TauMass
// -- slimmed --       VarHandle< Bool_t > EF_mu20i_tight_g5_medium_TauMass;
      /// Did this event pass trigger EF_mu20it_tight
      VarHandle< Bool_t > EF_mu20it_tight;
// -- slimmed --       /// Did this event pass trigger EF_mu22_IDTrkNoCut_tight
// -- slimmed --       VarHandle< Bool_t > EF_mu22_IDTrkNoCut_tight;
      /// Did this event pass trigger EF_mu24
      VarHandle< Bool_t > EF_mu24;
// -- slimmed --       /// Did this event pass trigger EF_mu24_g20vh_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu24_g20vh_loose;
// -- slimmed --       /// Did this event pass trigger EF_mu24_g20vh_medium
// -- slimmed --       VarHandle< Bool_t > EF_mu24_g20vh_medium;
      /// Did this event pass trigger EF_mu24_j65_a4tchad
      VarHandle< Bool_t > EF_mu24_j65_a4tchad;
      /// Did this event pass trigger EF_mu24_j65_a4tchad_EFxe40
      VarHandle< Bool_t > EF_mu24_j65_a4tchad_EFxe40;
      /// Did this event pass trigger EF_mu24_j65_a4tchad_EFxe40_tclcw
      VarHandle< Bool_t > EF_mu24_j65_a4tchad_EFxe40_tclcw;
      /// Did this event pass trigger EF_mu24_j65_a4tchad_EFxe60_tclcw
      VarHandle< Bool_t > EF_mu24_j65_a4tchad_EFxe60_tclcw;
      /// Did this event pass trigger EF_mu24_medium
      VarHandle< Bool_t > EF_mu24_medium;
// -- slimmed --       /// Did this event pass trigger EF_mu24_muCombTag_NoEF_tight
// -- slimmed --       VarHandle< Bool_t > EF_mu24_muCombTag_NoEF_tight;
      /// Did this event pass trigger EF_mu24_tight
      VarHandle< Bool_t > EF_mu24_tight;
      /// Did this event pass trigger EF_mu24_tight_3j35_a4tchad
      VarHandle< Bool_t > EF_mu24_tight_3j35_a4tchad;
      /// Did this event pass trigger EF_mu24_tight_EFxe40
      VarHandle< Bool_t > EF_mu24_tight_EFxe40;
// -- slimmed --       /// Did this event pass trigger EF_mu24_tight_L2StarB
// -- slimmed --       VarHandle< Bool_t > EF_mu24_tight_L2StarB;
// -- slimmed --       /// Did this event pass trigger EF_mu24_tight_L2StarC
// -- slimmed --       VarHandle< Bool_t > EF_mu24_tight_L2StarC;
      /// Did this event pass trigger EF_mu24_tight_MG
      VarHandle< Bool_t > EF_mu24_tight_MG;
      /// Did this event pass trigger EF_mu24_tight_MuonEF
      VarHandle< Bool_t > EF_mu24_tight_MuonEF;
      /// Did this event pass trigger EF_mu24_tight_b35_mediumEF_j35_a4tchad
      VarHandle< Bool_t > EF_mu24_tight_b35_mediumEF_j35_a4tchad;
      /// Did this event pass trigger EF_mu24_tight_mu6_EFFS
      VarHandle< Bool_t > EF_mu24_tight_mu6_EFFS;
      /// Did this event pass trigger EF_mu24i_tight
      VarHandle< Bool_t > EF_mu24i_tight;
      /// Did this event pass trigger EF_mu24i_tight_MG
      VarHandle< Bool_t > EF_mu24i_tight_MG;
      /// Did this event pass trigger EF_mu24i_tight_MuonEF
      VarHandle< Bool_t > EF_mu24i_tight_MuonEF;
// -- slimmed --       /// Did this event pass trigger EF_mu24i_tight_l2muonSA
// -- slimmed --       VarHandle< Bool_t > EF_mu24i_tight_l2muonSA;
      /// Did this event pass trigger EF_mu36_tight
      VarHandle< Bool_t > EF_mu36_tight;
// -- slimmed --       /// Did this event pass trigger EF_mu40_MSonly_barrel_tight
// -- slimmed --       VarHandle< Bool_t > EF_mu40_MSonly_barrel_tight;
// -- slimmed --       /// Did this event pass trigger EF_mu40_muCombTag_NoEF
// -- slimmed --       VarHandle< Bool_t > EF_mu40_muCombTag_NoEF;
// -- slimmed --       /// Did this event pass trigger EF_mu40_slow_outOfTime_tight
// -- slimmed --       VarHandle< Bool_t > EF_mu40_slow_outOfTime_tight;
// -- slimmed --       /// Did this event pass trigger EF_mu40_slow_tight
// -- slimmed --       VarHandle< Bool_t > EF_mu40_slow_tight;
      /// Did this event pass trigger EF_mu40_tight
      VarHandle< Bool_t > EF_mu40_tight;
// -- slimmed --       /// Did this event pass trigger EF_mu4T
// -- slimmed --       VarHandle< Bool_t > EF_mu4T;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_cosmic
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_cosmic;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j110_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j110_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j110_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j110_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j145_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j145_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j145_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j145_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j15_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j15_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j15_a4tchad_matchedZ
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j15_a4tchad_matchedZ;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j180_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j180_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j180_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j180_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j220_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j220_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j220_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j220_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j25_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j25_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j25_a4tchad_matchedZ
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j25_a4tchad_matchedZ;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j280_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j280_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j280_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j280_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j35_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j35_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j35_a4tchad_matchedZ
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j35_a4tchad_matchedZ;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j45_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j45_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j45_a4tchad_L2FS_matchedZ
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j45_a4tchad_L2FS_matchedZ;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j45_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j45_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j45_a4tchad_matchedZ
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j45_a4tchad_matchedZ;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j55_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j55_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j55_a4tchad_L2FS_matchedZ
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j55_a4tchad_L2FS_matchedZ;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j55_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j55_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j55_a4tchad_matchedZ
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j55_a4tchad_matchedZ;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j65_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j65_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j65_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j65_a4tchad_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j65_a4tchad_xe60_tclcw_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j65_a4tchad_xe60_tclcw_loose;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j65_a4tchad_xe70_tclcw_veryloose
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j65_a4tchad_xe70_tclcw_veryloose;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j80_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j80_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j80_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j80_a4tchad_matched;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Ti_g20Tvh_medium
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Ti_g20Tvh_medium;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Ti_g20Tvh_medium_TauMass
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Ti_g20Tvh_medium_TauMass;
// -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Bmumu
// -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Bmumu;
// -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Bmumu_Barrel
// -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Bmumu_Barrel;
// -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Bmumux
// -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Bmumux;
// -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Bmumux_Barrel
// -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Bmumux_Barrel;
// -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_DiMu
// -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_DiMu;
// -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_DiMu_Barrel
// -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_DiMu_Barrel;
// -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_DiMu_noVtx_noOS
// -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_DiMu_noVtx_noOS;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Jpsimumu
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Jpsimumu;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Jpsimumu_Barrel
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Jpsimumu_Barrel;
// -- slimmed -- // -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Jpsimumu_IDTrkNoCut
// -- slimmed -- // -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Jpsimumu_IDTrkNoCut;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Upsimumu
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Upsimumu;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Tmu6_Upsimumu_Barrel
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Tmu6_Upsimumu_Barrel;
// -- slimmed --       /// Did this event pass trigger EF_mu4_L1MU11_MSonly_cosmic
// -- slimmed --       VarHandle< Bool_t > EF_mu4_L1MU11_MSonly_cosmic;
      /// Did this event pass trigger EF_mu4_L1MU11_cosmic
      VarHandle< Bool_t > EF_mu4_L1MU11_cosmic;
// -- slimmed --       /// Did this event pass trigger EF_mu4_empty_NoAlg
// -- slimmed --       VarHandle< Bool_t > EF_mu4_empty_NoAlg;
// -- slimmed --       /// Did this event pass trigger EF_mu4_firstempty_NoAlg
// -- slimmed --       VarHandle< Bool_t > EF_mu4_firstempty_NoAlg;
// -- slimmed --       /// Did this event pass trigger EF_mu4_unpaired_iso_NoAlg
// -- slimmed --       VarHandle< Bool_t > EF_mu4_unpaired_iso_NoAlg;
// -- slimmed --       /// Did this event pass trigger EF_mu50_MSonly_barrel_tight
// -- slimmed --       VarHandle< Bool_t > EF_mu50_MSonly_barrel_tight;
      /// Did this event pass trigger EF_mu6
      VarHandle< Bool_t > EF_mu6;
// -- slimmed --       /// Did this event pass trigger EF_mu60_slow_outOfTime_tight1
// -- slimmed --       VarHandle< Bool_t > EF_mu60_slow_outOfTime_tight1;
// -- slimmed --       /// Did this event pass trigger EF_mu60_slow_tight1
// -- slimmed --       VarHandle< Bool_t > EF_mu60_slow_tight1;
// -- slimmed --       /// Did this event pass trigger EF_mu6_Jpsimumu_tight
// -- slimmed --       VarHandle< Bool_t > EF_mu6_Jpsimumu_tight;
// -- slimmed --       /// Did this event pass trigger EF_mu6_MSonly
// -- slimmed --       VarHandle< Bool_t > EF_mu6_MSonly;
// -- slimmed --       /// Did this event pass trigger EF_mu6_Trk_Jpsi_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu6_Trk_Jpsi_loose;
      /// Did this event pass trigger EF_mu8
      VarHandle< Bool_t > EF_mu8;
      /// Did this event pass trigger EF_mu8_4j45_a4tchad_L2FS
      VarHandle< Bool_t > EF_mu8_4j45_a4tchad_L2FS;


      // =============================================================================
      // = The lines below were picked up from the MC D3PD, but I think they will be
      // = applicable to data as well
      // =============================================================================
// -- slimmed --       /// Did this event pass trigger EF_2g15vh_loose_g10_loose
// -- slimmed --       VarHandle< Bool_t > EF_2g15vh_loose_g10_loose;
// -- slimmed --       /// Did this event pass trigger EF_2g15vh_medium
// -- slimmed --       VarHandle< Bool_t > EF_2g15vh_medium;
// -- slimmed --       /// Did this event pass trigger EF_2g20_loose
// -- slimmed --       VarHandle< Bool_t > EF_2g20_loose;
// -- slimmed --       /// Did this event pass trigger EF_2g30_loose
// -- slimmed --       VarHandle< Bool_t > EF_2g30_loose;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu10_MSonly_g10_loose_EMPTY
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu10_MSonly_g10_loose_EMPTY;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_2mu10_MSonly_g10_loose_UNPAIRED_ISO
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_2mu10_MSonly_g10_loose_UNPAIRED_ISO;
// -- slimmed --       /// Did this event pass trigger EF_2mu4T_xe50_tclcw
// -- slimmed --       VarHandle< Bool_t > EF_2mu4T_xe50_tclcw;
      /// Did this event pass trigger EF_e12Tvh_loose1_mu8
      VarHandle< Bool_t > EF_e12Tvh_loose1_mu8;
      /// Did this event pass trigger EF_e12Tvh_medium1_mu10
      VarHandle< Bool_t > EF_e12Tvh_medium1_mu10;
      /// Did this event pass trigger EF_e12Tvh_medium1_mu6
      VarHandle< Bool_t > EF_e12Tvh_medium1_mu6;
// -- slimmed --       /// Did this event pass trigger EF_e18_loose1_g35_loose
// -- slimmed --       VarHandle< Bool_t > EF_e18_loose1_g35_loose;
// -- slimmed --       /// Did this event pass trigger EF_e18_loose1_g35_medium
// -- slimmed --       VarHandle< Bool_t > EF_e18_loose1_g35_medium;
// -- slimmed --       /// Did this event pass trigger EF_e18_medium1_g25_medium
// -- slimmed --       VarHandle< Bool_t > EF_e18_medium1_g25_medium;
// -- slimmed --       /// Did this event pass trigger EF_e18_medium1_g35_loose
// -- slimmed --       VarHandle< Bool_t > EF_e18_medium1_g35_loose;
// -- slimmed --       /// Did this event pass trigger EF_e18_medium1_g35_medium
// -- slimmed --       VarHandle< Bool_t > EF_e18_medium1_g35_medium;
      /// Did this event pass trigger EF_e22vh_medium1_IdScan
      VarHandle< Bool_t > EF_e22vh_medium1_IdScan;
      /// Did this event pass trigger EF_e22vh_medium1_SiTrk
      VarHandle< Bool_t > EF_e22vh_medium1_SiTrk;
      /// Did this event pass trigger EF_e22vh_medium1_TRT
      VarHandle< Bool_t > EF_e22vh_medium1_TRT;
      /// Did this event pass trigger EF_e45_etcut
      VarHandle< Bool_t > EF_e45_etcut;
// -- slimmed --       /// Did this event pass trigger EF_e5_tight1_e4_etcut_Jpsi_IdScan
// -- slimmed --       VarHandle< Bool_t > EF_e5_tight1_e4_etcut_Jpsi_IdScan;
// -- slimmed --       /// Did this event pass trigger EF_e5_tight1_e4_etcut_Jpsi_SiTrk
// -- slimmed --       VarHandle< Bool_t > EF_e5_tight1_e4_etcut_Jpsi_SiTrk;
// -- slimmed --       /// Did this event pass trigger EF_e5_tight1_e4_etcut_Jpsi_TRT
// -- slimmed --       VarHandle< Bool_t > EF_e5_tight1_e4_etcut_Jpsi_TRT;
      /// Did this event pass trigger EF_e60_etcut
      VarHandle< Bool_t > EF_e60_etcut;
// -- slimmed --       /// Did this event pass trigger EF_g12Tvh_medium
// -- slimmed --       VarHandle< Bool_t > EF_g12Tvh_medium;
// -- slimmed --       /// Did this event pass trigger EF_g15vh_loose
// -- slimmed --       VarHandle< Bool_t > EF_g15vh_loose;
// -- slimmed --       /// Did this event pass trigger EF_g20Tvh_medium
// -- slimmed --       VarHandle< Bool_t > EF_g20Tvh_medium;
// -- slimmed --       /// Did this event pass trigger EF_g20vh_medium
// -- slimmed --       VarHandle< Bool_t > EF_g20vh_medium;
// -- slimmed --       /// Did this event pass trigger EF_g40_loose_EFxe50
// -- slimmed --       VarHandle< Bool_t > EF_g40_loose_EFxe50;
// -- slimmed --       /// Did this event pass trigger EF_g40_loose_L2EFxe50
// -- slimmed --       VarHandle< Bool_t > EF_g40_loose_L2EFxe50;
// -- slimmed --       /// Did this event pass trigger EF_mu10i_g10_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu10i_g10_loose;
// -- slimmed --       /// Did this event pass trigger EF_mu10i_g10_loose_TauMass
// -- slimmed --       VarHandle< Bool_t > EF_mu10i_g10_loose_TauMass;
// -- slimmed --       /// Did this event pass trigger EF_mu10i_loose_g12Tvh_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu10i_loose_g12Tvh_loose;
// -- slimmed --       /// Did this event pass trigger EF_mu10i_loose_g12Tvh_loose_TauMass
// -- slimmed --       VarHandle< Bool_t > EF_mu10i_loose_g12Tvh_loose_TauMass;
// -- slimmed --       /// Did this event pass trigger EF_mu18_2g15_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu18_2g15_loose;
// -- slimmed --       /// Did this event pass trigger EF_mu18_g20vh_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu18_g20vh_loose;
      /// Did this event pass trigger EF_mu18it_tight
      VarHandle< Bool_t > EF_mu18it_tight;
// -- slimmed --       /// Did this event pass trigger EF_mu20i_tight_g5_loose
// -- slimmed --       VarHandle< Bool_t > EF_mu20i_tight_g5_loose;
      /// Did this event pass trigger EF_mu24_j65_a4tchad_EFxe50_tclcw
      VarHandle< Bool_t > EF_mu24_j65_a4tchad_EFxe50_tclcw;
      /// Did this event pass trigger EF_mu24_tight_2j35_a4tchad
      VarHandle< Bool_t > EF_mu24_tight_2j35_a4tchad;
      /// Did this event pass trigger EF_mu24_tight_4j35_a4tchad
      VarHandle< Bool_t > EF_mu24_tight_4j35_a4tchad;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4T_Trk_Jpsi
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4T_Trk_Jpsi;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j360_a4tchad_L2FS_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j360_a4tchad_L2FS_matched;
// -- slimmed --       /// Did this event pass trigger EF_mu4T_j360_a4tchad_matched
// -- slimmed --       VarHandle< Bool_t > EF_mu4T_j360_a4tchad_matched;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Ti_g20Tvh_loose
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Ti_g20Tvh_loose;
// -- slimmed -- // -- slimmed --       /// Did this event pass trigger EF_mu4Ti_g20Tvh_loose_TauMass
// -- slimmed -- // -- slimmed --       VarHandle< Bool_t > EF_mu4Ti_g20Tvh_loose_TauMass;
      /// Did this event pass trigger EF_mu6i
      VarHandle< Bool_t > EF_mu6i;

   private:
      std::map< ::TString, VarHandleBase* > fHandles; ///< Book-keeper of the VarHandle members
      const ::Bool_t fFromInput; ///< Flag specifying if object is used for D3PD reading
      const ::TString fPrefix; ///< Prefix to the branch names

      ClassDef( TriggerD3PDObject, 0 )

   }; // class TriggerD3PDObject

} // namespace D3PDReader

#endif // D3PDREADER_TriggerD3PDObject_H
