# imported config files
cut_config:  /afs/cern.ch/user/b/bjackson/work/private/Susy.00.03.04/SFrame/../utils/RunConfigs/tnt.022/mm.sr_ss/cuts/cuts.optimize.mm.sr_ss.data.config
hist_config: /afs/cern.ch/user/b/bjackson/work/private/Susy.00.03.04/SFrame/../utils/RunConfigs/tnt.022/mm.sr_ss/hists/hists.optimize.mm.sr_ss.config

# other settings
# target_lumi: 21000
target_lumi: 13000
lumi_weight: 0

in_tree: output
max_job_size: 5
file_name_base: data
ptnt_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/Susy.00.03.04/utils/pTNTs/OptimizationHistograms/tnt.022/mm.sr_ss/
hist_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/Susy.00.03.04/utils/hists/OptimizationHistograms/tnt.022/mm.sr_ss/

in_file_base_path: /afs/cern.ch/user/b/bjackson/eos_mount/atlas/user/b/bjackson/tnt.022/
in_files:
  # Data - Muon stream
  Muon.periodA:
    sample_number: Muon.periodA
    grep_for:      Muon.periodA
  Muon.periodB:
    sample_number: Muon.periodB
    grep_for:      Muon.periodB
  Muon.periodC:
    sample_number: Muon.periodC
    grep_for:      Muon.periodC
  Muon.periodD:
    sample_number: Muon.periodD
    grep_for:      Muon.periodD
  Muon.periodE:
    sample_number: Muon.periodE
    grep_for:      Muon.periodE
  # Muon.periodG:
  #   sample_number: Muon.periodG
  #   grep_for:      Muon.periodG
  # Muon.periodH:
  #   sample_number: Muon.periodH
  #   grep_for:      Muon.periodH
  # Muon.periodI:
  #   sample_number: Muon.periodI
  #   grep_for:      Muon.periodI
  # Muon.periodJ:
  #   sample_number: Muon.periodJ
  #   grep_for:      Muon.periodJ
  # Muon.periodL:
  #   sample_number: Muon.periodL
  #   grep_for:      Muon.periodL

