# imported config files
cut_config:  /afs/cern.ch/user/b/bjackson/work/private/PennSusyFrame.00.03.06/utils/RunConfigs/IsolationTests/cuts/cuts.iso_test.nominal.config
hist_config: /afs/cern.ch/user/b/bjackson/work/private/PennSUSYFrame.00.03.06/utils/RunConfigs/IsolationTests/hists/hists.iso_test.config

# other settings
# target_lumi: 21000
target_lumi: 13000
lumi_weight: 0

in_tree: output
max_job_size: 5
file_name_base: data
ptnt_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/PennSusyFrame.00.03.06/utils/pTNTs/IsolationTests/IsoTest/
hist_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/PennSusyFrame.00.03.06/utils/hists/IsolationTests/IsoTest/

in_file_base_path: /afs/cern.ch/user/b/bjackson/eos_mount/atlas/user/b/bjackson/tnt.022/
in_files:
  # Data - Muon stream
  Muon.periodA:
    sample_number: Muon.periodA
    grep_for:      Muon.periodA
  Muon.periodB:
    sample_number: Muon.periodB
    grep_for:      Muon.periodB
  Muon.periodC:
    sample_number: Muon.periodC
    grep_for:      Muon.periodC
  Muon.periodD:
    sample_number: Muon.periodD
    grep_for:      Muon.periodD
  Muon.periodE:
    sample_number: Muon.periodE
    grep_for:      Muon.periodE
  Muon.periodA:
    sample_number: Muon.periodA
    grep_for:      Muon.periodA
  Egamma.periodA:
    sample_number: Egamma.periodA
    grep_for:      Egamma.periodA
  Egamma.periodB:
    sample_number: Egamma.periodB
    grep_for:      Egamma.periodB
  Egamma.periodC:
    sample_number: Egamma.periodC
    grep_for:      Egamma.periodC
  Egamma.periodD:
    sample_number: Egamma.periodD
    grep_for:      Egamma.periodD
  Egamma.periodE:
    sample_number: Egamma.periodE
    grep_for:      Egamma.periodE

