# imported config files
cut_config:  /afs/cern.ch/user/b/bjackson/work/private/PennSusyFrame.00.03.06/utils/RunConfigs/IsolationTests/cuts/cuts.iso_test.nominal.config
hist_config: /afs/cern.ch/user/b/bjackson/work/private/PennSUSYFrame.00.03.06/utils/RunConfigs/IsolationTests/hists/hists.iso_test.config

# other settings
# target_lumi: 21000
target_lumi: 13000

in_tree: output
max_job_size: 5
file_name_base: nominal
ptnt_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/PennSusyFrame.00.03.06/utils/pTNTs/IsolationTests/IsoTest/
hist_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/PennSusyFrame.00.03.06/utils/hists/IsolationTests/IsoTest/

in_file_base_path: /afs/cern.ch/user/b/bjackson/eos_mount/atlas/user/b/bjackson/tnt.022/
in_files:
  # ZX - AlpgenPythia
  ZX__AlpgenPythia.117650.AlpgenPythia_P2011C_ZeeNp0:
    sample_number: 117650
    grep_for:      ZX__AlpgenPythia.117650.AlpgenPythia_P2011C_ZeeNp0
  ZX__AlpgenPythia.117651.AlpgenPythia_P2011C_ZeeNp1:
    sample_number: 117651
    grep_for:      ZX__AlpgenPythia.117651.AlpgenPythia_P2011C_ZeeNp1
  ZX__AlpgenPythia.117652.AlpgenPythia_P2011C_ZeeNp2:
    sample_number: 117652
    grep_for:      ZX__AlpgenPythia.117652.AlpgenPythia_P2011C_ZeeNp2
  ZX__AlpgenPythia.117653.AlpgenPythia_P2011C_ZeeNp3:
    sample_number: 117653
    grep_for:      ZX__AlpgenPythia.117653.AlpgenPythia_P2011C_ZeeNp3
  ZX__AlpgenPythia.117654.AlpgenPythia_P2011C_ZeeNp4:
    sample_number: 117654
    grep_for:      ZX__AlpgenPythia.117654.AlpgenPythia_P2011C_ZeeNp4
  ZX__AlpgenPythia.117655.AlpgenPythia_P2011C_ZeeNp5:
    sample_number: 117655
    grep_for:      ZX__AlpgenPythia.117655.AlpgenPythia_P2011C_ZeeNp5
  ZX__AlpgenPythia.117660.AlpgenPythia_P2011C_ZmumuNp0:
    sample_number: 117660
    grep_for:      ZX__AlpgenPythia.117660.AlpgenPythia_P2011C_ZmumuNp0
  ZX__AlpgenPythia.117661.AlpgenPythia_P2011C_ZmumuNp1:
    sample_number: 117661
    grep_for:      ZX__AlpgenPythia.117661.AlpgenPythia_P2011C_ZmumuNp1
  ZX__AlpgenPythia.117662.AlpgenPythia_P2011C_ZmumuNp2:
    sample_number: 117662
    grep_for:      ZX__AlpgenPythia.117662.AlpgenPythia_P2011C_ZmumuNp2
  ZX__AlpgenPythia.117663.AlpgenPythia_P2011C_ZmumuNp3:
    sample_number: 117663
    grep_for:      ZX__AlpgenPythia.117663.AlpgenPythia_P2011C_ZmumuNp3
  ZX__AlpgenPythia.117664.AlpgenPythia_P2011C_ZmumuNp4:
    sample_number: 117664
    grep_for:      ZX__AlpgenPythia.117664.AlpgenPythia_P2011C_ZmumuNp4
  ZX__AlpgenPythia.117665.AlpgenPythia_P2011C_ZmumuNp5:
    sample_number: 117665
    grep_for:      ZX__AlpgenPythia.117665.AlpgenPythia_P2011C_ZmumuNp5

