
Type:             mc
OutputLevel:      INFO
OutputDirectory:  ${PWD}/small_fake_test/
NEventsMax:       -1
is_af2:           True
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       105200.ttbar.cf_challenge

input_tree_name:  susy
output_tree_name: output
is_egamma_stream: True

UserConfigFile: ${SFRAME_DIR}/../run/local_configs/user_config.cut_flow.mc.small_fakes.yml

InputFiles:
  - /afs/cern.ch/user/b/bjackson/work/private/mc12/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.merge.NTUP_SUSY.e1513_a159_a171_r3549_p1512_tid01267512_00/NTUP_SUSY.01267512._000025.root.1
  - /afs/cern.ch/user/b/bjackson/work/private/mc12/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.merge.NTUP_SUSY.e1513_a159_a171_r3549_p1512_tid01267512_00/NTUP_SUSY.01267512._000040.root.1
  - /afs/cern.ch/user/b/bjackson/work/private/mc12/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.merge.NTUP_SUSY.e1513_a159_a171_r3549_p1512_tid01267513_00/NTUP_SUSY.01267513._000156.root.1
  - /afs/cern.ch/user/b/bjackson/work/private/mc12/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.merge.NTUP_SUSY.e1513_a159_a171_r3549_p1512_tid01267513_00/NTUP_SUSY.01267513._000231.root.1
  - /afs/cern.ch/user/b/bjackson/work/private/mc12/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.merge.NTUP_SUSY.e1513_a159_a171_r3549_p1512_tid01267514_00/NTUP_SUSY.01267514._000504.root.1

