
Type:             mc
OutputLevel:      INFO
OutputDirectory:  ${PWD}/small_fake_test/
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       116600.ZZ4lep

input_tree_name:  susy
output_tree_name: output
is_egamma_stream: True

PrintEventInfo:     True

UserConfigFile: ${SFRAME_DIR}/../run/local_configs/user_config.cut_flow.mc.small_fakes.yml

InputFiles:
  - /tmp/bjackson/mc12_8TeV.116600.gg2ZZJimmy_AUET2CT10_ZZ4lep.merge.NTUP_SUSY.e1525_s1499_s1504_r3658_r3549_p1512_tid01267663_00/NTUP_SUSY.01267663._000001.root.1
  - /tmp/bjackson/mc12_8TeV.116600.gg2ZZJimmy_AUET2CT10_ZZ4lep.merge.NTUP_SUSY.e1525_s1499_s1504_r3658_r3549_p1512_tid01267663_00/NTUP_SUSY.01267663._000002.root.1
  - /tmp/bjackson/mc12_8TeV.116600.gg2ZZJimmy_AUET2CT10_ZZ4lep.merge.NTUP_SUSY.e1525_s1499_s1504_r3658_r3549_p1512_tid01267663_00/NTUP_SUSY.01267663._000003.root.1
  - /tmp/bjackson/mc12_8TeV.116600.gg2ZZJimmy_AUET2CT10_ZZ4lep.merge.NTUP_SUSY.e1525_s1499_s1504_r3658_r3549_p1512_tid01267663_00/NTUP_SUSY.01267663._000004.root.1



