# ------------------------------------------------------------------------------
Optimize:
  - cut_dir:     mm_sr_ssjets__sample2.SR_SSJets_preMt
    to_optimize: mt
    direction:   left
    scan:        0 
    fixed_points:
      - 0
      - 10
      - 20
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100
  - cut_dir:     mm_sr_ssjets__sample8.SR_SSJets
    to_optimize: mll
    direction:   right
    scan:        0 
    fixed_points:
      - 0
  - cut_dir:     mm_sr_ssjets__sample9.SR_SSJets.mu_pt_10
    to_optimize: mll
    direction:   right
    scan:        0 
    fixed_points:
      - 0
  - cut_dir:     mm_sr_ssjets__sample10.SR_SSJets.mu_pt_15
    to_optimize: mll
    direction:   right
    scan:        0 
    fixed_points:
      - 0
  - cut_dir:     mm_sr_ssjets__sample11.SR_SSJets.mu_pt_20
    to_optimize: mll
    direction:   right
    scan:        0 
    fixed_points:
      - 0
  - cut_dir:     mm_sr_ssjets__sample12.SR_SSJets.mu_pt_25
    to_optimize: mll
    direction:   right
    scan:        0 
    fixed_points:
      - 0

# ------------------------------------------------------------------------------
Inputs:
  - class: Signal_simplifiedModel_wA_slep_noWcascade_5
    name: simplifiedModel_wA_slep_noWcascade_5
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_5.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_7
    name: simplifiedModel_wA_slep_noWcascade_7
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_7.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_8
    name: simplifiedModel_wA_slep_noWcascade_8
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_8.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_10
    name: simplifiedModel_wA_slep_noWcascade_10
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_10.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_11
    name: simplifiedModel_wA_slep_noWcascade_11
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_11.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_13
    name: simplifiedModel_wA_slep_noWcascade_13
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_13.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_14
    name: simplifiedModel_wA_slep_noWcascade_14
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_14.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_15
    name: simplifiedModel_wA_slep_noWcascade_15
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_15.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_17
    name: simplifiedModel_wA_slep_noWcascade_17
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_17.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_18
    name: simplifiedModel_wA_slep_noWcascade_18
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_18.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_19
    name: simplifiedModel_wA_slep_noWcascade_19
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_19.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_20
    name: simplifiedModel_wA_slep_noWcascade_20
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_20.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_22
    name: simplifiedModel_wA_slep_noWcascade_22
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_22.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_23
    name: simplifiedModel_wA_slep_noWcascade_23
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_23.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_24
    name: simplifiedModel_wA_slep_noWcascade_24
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_24.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_25
    name: simplifiedModel_wA_slep_noWcascade_25
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_25.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_26
    name: simplifiedModel_wA_slep_noWcascade_26
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_26.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_28
    name: simplifiedModel_wA_slep_noWcascade_28
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_28.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_29
    name: simplifiedModel_wA_slep_noWcascade_29
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_29.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_30
    name: simplifiedModel_wA_slep_noWcascade_30
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_30.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_32
    name: simplifiedModel_wA_slep_noWcascade_32
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_32.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_35
    name: simplifiedModel_wA_slep_noWcascade_35
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_35.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_38
    name: simplifiedModel_wA_slep_noWcascade_38
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_38.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_39
    name: simplifiedModel_wA_slep_noWcascade_39
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_39.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_40
    name: simplifiedModel_wA_slep_noWcascade_40
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_40.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_41
    name: simplifiedModel_wA_slep_noWcascade_41
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_41.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_42
    name: simplifiedModel_wA_slep_noWcascade_42
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_42.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_43
    name: simplifiedModel_wA_slep_noWcascade_43
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_43.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_44
    name: simplifiedModel_wA_slep_noWcascade_44
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_44.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_45
    name: simplifiedModel_wA_slep_noWcascade_45
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_45.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_46
    name: simplifiedModel_wA_slep_noWcascade_46
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_46.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_47
    name: simplifiedModel_wA_slep_noWcascade_47
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_47.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_48
    name: simplifiedModel_wA_slep_noWcascade_48
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_48.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_49
    name: simplifiedModel_wA_slep_noWcascade_49
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_49.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_50
    name: simplifiedModel_wA_slep_noWcascade_50
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_50.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_51
    name: simplifiedModel_wA_slep_noWcascade_51
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_51.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_52
    name: simplifiedModel_wA_slep_noWcascade_52
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_52.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Signal_simplifiedModel_wA_slep_noWcascade_53
    name: simplifiedModel_wA_slep_noWcascade_53
    fill_color: 1
    line_color: 1
    line_width: 2
    line_style: 2
    marker_style: 20
    modeled: 13
    target:  21
    entries:
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/signal/signal_simplified.simplifiedModel_wA_slep_noWcascade_53.__Herwigpp_UEEE3_CTEQ6L1.yml

  - class: Background
    name: Background
    fill_color: 2
    line_color: 2
    line_width: 2
    line_style: 1
    marker_style: 21
    modeled: 13
    target:  21
    entries:
          # Diboson
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/background/diboson__PowhegPythia8_AU2CT10.yml
            # - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/background/diboson__Sherpa_CT10.yml

          # Fake
          - !include /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/Plotting/configs/tnt.009/entry_files/background/fake_muon.yml
