# imported config files
cut_config:  /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/SFrame/../utils/RunConfigs/tnt.010.v3/mm.sr_ssjets/cuts/cuts.optimize.mm.sr_ssjets.data.config
hist_config: /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/SFrame/../utils/RunConfigs/tnt.010.v3/mm.sr_ssjets/hists/hists.optimize.mm.sr_ssjets.config

# other settings
# target_lumi: 21000
target_lumi: 13000
lumi_weight: 0

in_tree: output
max_job_size: 10
file_name_base: data
ptnt_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/pTNTs/OptimizationHistograms/tnt.010.v3/mm.sr_ssjets/
hist_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.010.v3/mm.sr_ssjets/

in_file_base_path: /afs/cern.ch/user/b/bjackson/eos_mount/atlas/user/b/bjackson/tnt.010.v3/
in_files:
  # Data - Muon stream
  Muon.periodA:
    sample_number: Muon.periodA
    grep_for: Muon.periodA
  Muon.periodB:
    sample_number: Muon.periodB
    grep_for: Muon.periodB
  Muon.periodC:
    sample_number: Muon.periodC
    grep_for: Muon.periodC
  Muon.periodD:
    sample_number: Muon.periodD
    grep_for: Muon.periodD
  Muon.periodE:
    sample_number: Muon.periodE
    grep_for: Muon.periodE
  # Muon.periodG:
  #   sample_number: Muon.periodG
  #   grep_for: Muon.periodG
  # Muon.periodH:
  #   sample_number: Muon.periodH
  #   grep_for: Muon.periodH
  # Muon.periodI:
  #   sample_number: Muon.periodI
  #   grep_for: Muon.periodI
  # Muon.periodJ:
  #   sample_number: Muon.periodJ
  #   grep_for: Muon.periodJ
  # Muon.periodL:
  #   sample_number: Muon.periodL
  #   grep_for: Muon.periodL
