# Package information
LIBRARY = TinyTlv
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include
# EXECUTABLE := $(PWD)/TinyTlv

# LOCAL_LIBS_PATH =  $(SH_LIB_PATH)/libProgressBar.so
# BONUS_LIB_PATH = 

INCLUDES += -I../
INCLUDES += -I./
INCLUDES += -I../../

# Include the generic compilation rules
include $(PWD)/../Makefile.common
