Inputs:
  - class: Numerator
    name: Data
    fill_color: 1
    line_color: 1
    marker_style: 20
    entries:
          - label: Data_1
            fill_color: 1
            line_color: 1
            marker_style: 20
            inputs:
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root


  - class: Denominator
    name: Background
    fill_color: 2
    line_color: 2
    marker_style: 21
    entries:
          - label:        BG_1
            fill_color:   821
            line_color:   1
            marker_style: 22
            inputs:
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
          - label:        BG_2
            fill_color:   920
            line_color:   1
            marker_style: 22
            inputs:
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root

  - class: Other
    name: Signal
    fill_color: 1
    line_color: 1
    marker_style: 20
    entries:
          - label: signal_1
            fill_color: 0
            line_color: 46
            marker_style: 20
            inputs:
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
          - label: signal_2
            fill_color: 0
            line_color: 40
            marker_style: 20
            inputs:
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
          - label: signal_3
            fill_color: 0
            line_color: 38
            marker_style: 20
            inputs:
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
              - /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.008/mm.sr_ssjets/hist.nominal.diboson.126893.Sherpa_CT10_lllnu_WZ.__merge.root
