
Type:             mc
OutputLevel:      INFO
OutputDirectory:  /exports/project/data_d07_3/bjackson/Susy_output/00.02.04/
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       PowhegPythia8_AU2CT10_WZ_Wm11Z15_mll3p804d0_2LeptonFilter5

input_tree_name:  susy
output_tree_name: output
is_egamma_stream: True


# UserConfigFile: /exports/project/data_d07_3/ehines/SusyFrame/Susy_p1328/SFrame/../run/pcpenn_configs/user_config.cut_flow.mc.yml
UserConfigFile: ${SFRAME_DIR}/../run/pcpenn_configs/user_config.cut_flow.mc.yml
InputFiles:
  - /exports/project/data_d07_4/ehines/2012MC//mc12_8TeV.129479.PowhegPythia8_AU2CT10_WZ_Wm11Z15_mll3p804d0_2LeptonFilter5.merge.NTUP_SUSY.e1300_s1469_s1470_r3542_r3549_p1328_tid01116329_00/NTUP_SUSY.01116329._000007.root.1
