# Package information
LIBRARY = CommonTools
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

INCLUDES += -I../
INCLUDES += -I./
#INCLUDES += -I../RootCore/JetResolution/
INCLUDES += -I../RootCore/MuonEfficiencyCorrections/
INCLUDES += -I../RootCore/PileupReweighting/
INCLUDES += -I../RootCore/ReweightUtils/
INCLUDES += -I../RootCore/SUSYTools/
INCLUDES += -I../RootCore/ApplyJetCalibration/
INCLUDES += -I../RootCore/JetUncertainties/
INCLUDES += -I../RootCore/MissingETUtility/
INCLUDES += -I../RootCore/MuonMomentumCorrections/
INCLUDES += -I../RootCore/egammaAnalysisUtils/
INCLUDES += -I../RootCore/LeptonTruthTools/
INCLUDES += -I../RootCore/ChargeFlip/
# INCLUDES += -I../RootCore/egammaAnalysisUtils/
INCLUDES += -I../RootCore/egammaEvent/
INCLUDES += -I../RootCore/DGTriggerReweight/
INCLUDES += -I../RootCore/ElectronEfficiencyCorrection
INCLUDES += -I../RootCore/PATCore
# Include the generic compilation rules
include $(SFRAME_DIR)/Makefile.common
