# Package information
LIBRARY = CommonTools
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

INCLUDES += -I../
INCLUDES += -I./
INCLUDES += -I../RootCore/egammaAnalysisUtils/
#INCLUDES += -I../RootCore/JetResolution/
#INCLUDES += -I../RootCore/MuonEfficiencyCorrections/
#INCLUDES += -I../RootCore/MuonMomentumCorrections/
#INCLUDES += -I../RootCore/SUSYTools/
#INCLUDES += -I../RootCore/PileupReweighting/
#INCLUDES += -I../RootCore/ReweightUtils/
#INCLUDES += -I../RootCore/MissingETUtility/
#INCLUDES += -I../RootCore/ApplyJetCalibration/

# Include the generic compilation rules
include $(SFRAME_DIR)/Makefile.common
