# Package information
LIBRARY = PennSusyFrameCore
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include
EXECUTABLE := $(PWD)/PennSusyFrameCore

INCLUDES += -I../
INCLUDES += -I./
INCLUDES += -I../../

# Include the generic compilation rules
include $(PWD)/../Makefile.common
