Type:             MC
OutputLevel:      INFO
OutputDirectory:  ./
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonPreselCycle
SampleName:       105200.ttbar_small

input_tree_name:  susy
output_tree_name: presel
is_egamma_stream: True

UserConfigFile: ${SFRAME_DIR}/../scripts/run_scripts/user_config.presel.mc.yml
InputFiles:
  - ~/work/mc12/mc12_8TeV.105200.McAtNloJimmy_CT10_ttbar_LeptonFilter.merge.NTUP_SUSY.e1193_s1469_s1470_r3542_r3549_p1181_tid00950213_00/NTUP_SUSY.00950213._000715.root.1
