
Type:             mc
OutputLevel:      INFO
OutputDirectory:  /exports/project/data_d07_3/${USER}/Susy_output/00.02.05/
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       126893.Sherpa_CT10_lllnu_WZ

input_tree_name:  susy
output_tree_name: output
is_egamma_stream: True


# UserConfigFile: /exports/project/data_d07_3/ehines/SusyFrame/Susy_p1328/SFrame/../run/pcpenn_configs/user_config.cut_flow.mc.yml
UserConfigFile: ${SFRAME_DIR}/../run/pcpenn_configs/user_config.cut_flow.mc.yml
InputFiles:
  - /exports/project/data_d07_3/bjackson/mc12/mc12_8TeV.126893.Sherpa_CT10_lllnu_WZ.merge.NTUP_SUSY.e1434_s1499_s1504_r3658_r3549_p1328_tid01116019_00/NTUP_SUSY.01116019._000001.root.1
