# imported config files
cut_config:  /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/SFrame/../utils/RunConfigs/tnt.009/em.sr_ssjets/cuts.optimize.em.sr_ssjets.data.config
hist_config: /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/SFrame/../utils/RunConfigs/tnt.009/em.sr_ssjets/hists.optimize.em.sr_ssjets.config

# other settings
# target_lumi: 21000
target_lumi: 13000
lumi_weight: 0

in_tree: output
max_job_size: 50
file_name_base: data
ptnt_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/pTNTs/OptimizationHistograms/tnt.009/em.sr_ssjets/
hist_out_file_path: /afs/cern.ch/user/b/bjackson/work/private/Susy_lxplus.00.02.08/utils/hists/OptimizationHistograms/tnt.009/em.sr_ssjets/

in_file_base_path: /afs/cern.ch/user/b/bjackson/eos_mount/atlas/user/b/bjackson/tnt.009/
in_files:
  # Data - Egamma stream
  Egamma.periodA:
    sample_number: Egamma.periodA
    grep_for: Egamma.periodA
  Egamma.periodB:
    sample_number: Egamma.periodB
    grep_for: Egamma.periodB
  Egamma.periodC:
    sample_number: Egamma.periodC
    grep_for: Egamma.periodC
  Egamma.periodD:
    sample_number: Egamma.periodD
    grep_for: Egamma.periodD
  Egamma.periodE:
    sample_number: Egamma.periodE
    grep_for: Egamma.periodE

  # Data - Muon stream
  Muon.periodA:
    sample_number: Muon.periodA
    grep_for: Muon.periodA
  Muon.periodB:
    sample_number: Muon.periodB
    grep_for: Muon.periodB
  Muon.periodC:
    sample_number: Muon.periodC
    grep_for: Muon.periodC
  Muon.periodD:
    sample_number: Muon.periodD
    grep_for: Muon.periodD
  Muon.periodE:
    sample_number: Muon.periodE
    grep_for: Muon.periodE
