
Type:             mc
OutputLevel:      INFO
OutputDirectory:  ${PWD}/small_fake_test/
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       117664.ZmumuNp4

input_tree_name:  susy
output_tree_name: output
is_egamma_stream: True

UserConfigFile: ${SFRAME_DIR}/../run/local_configs/user_config.cut_flow.mc.small_fakes.yml

InputFiles:
    - /tmp/bjackson/mc12_8TeV.117664.AlpgenPythia_P2011C_ZmumuNp4.merge.NTUP_SUSY.e1477_s1499_s1504_r3658_r3549_p1512_tid01267680_00/NTUP_SUSY.01267680._000001.root.1
    - /tmp/bjackson/mc12_8TeV.117664.AlpgenPythia_P2011C_ZmumuNp4.merge.NTUP_SUSY.e1477_s1499_s1504_r3658_r3549_p1512_tid01267680_00/NTUP_SUSY.01267680._000002.root.1
    - /tmp/bjackson/mc12_8TeV.117664.AlpgenPythia_P2011C_ZmumuNp4.merge.NTUP_SUSY.e1477_s1499_s1504_r3658_r3549_p1512_tid01267680_00/NTUP_SUSY.01267680._000003.root.1
