Type:             mc
OutputLevel:      INFO
OutputDirectory:  /disk/userdata00/atlas_data2/${USER}/SUSY/00.02.05/
NEventsMax:       -1
is_af2:           False
SuperVerboseInfo: False
PrintEventInfo:   False
Version:          1
CycleName:        SusyDiLeptonCutFlowCycle
SampleName:       Z_plus_jet.107653.AlpgenJimmy_AUET2CTEQ6L1_ZeeNp3

input_tree_name:  presel
output_tree_name: output
is_egamma_stream: True


UserConfigFile: /home/elhines/Susy_presel_12Feb/SFrame/../run/tier3_configs/user_config.cut_flow.mc.yml
InputFiles:
 - root://hn.at3f//srm/atlaslocalgroupdisk/user/bjackson/mc12_8TeV//user.bjackson.mc12_8TeV.Z_plus_jet.107653.AlpgenJimmy_AUET2CTEQ6L1_ZeeNp3.presel.presel.51.130213153235/user.bjackson.012415._00001.SusyDiLeptonPreselCycle.mc.ver_1.presel..root
 - root://hn.at3f//srm/atlaslocalgroupdisk/user/bjackson/mc12_8TeV//user.bjackson.mc12_8TeV.Z_plus_jet.107653.AlpgenJimmy_AUET2CTEQ6L1_ZeeNp3.presel.presel.51.130213153235/user.bjackson.012415._00001.SusyDiLeptonPreselCycle.mc.ver_1.presel..root
