# Package information
LIBRARY = D3PDObjects
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include
# EXECUTABLE := $(PWD)/

INCLUDES += -I../
INCLUDES += -I./
INCLUDES += -I../../

# Include the generic compilation rules
include $(PWD)/../Makefile.common
