LIBRARY := EventNumberDump
OBJDIR  := $(PWD)/obj
SRCDIR  := $(PWD)/src
INCDIR  := $(PWD)/include
EXECUTABLE := $(PWD)/EventNumberDump
BONUS_LIB_PATH := $(SFRAME_LIB_PATH)/libSusyAnalysisTools.so

INCLUDES += -I../
INCLUDES += -I./
INCLUDES += -I../../

include $(PWD)/../Makefile.common
